import {STORAGE_KEY, initialState, validateState, records, dailyTasks, today, taskLimit, rolloverCandidates, activeGoals, put, uid, makeBackup, mergeStates, dayDifference, addDays, goalStatus, goalProgress, planWindow, planDayProgress, saveGoal, goalHistory, executionDays, carryTask, parkedTasks, focusParked} from './core.js?v=20261009-r5';
import {CloudSync, loadConfig, saveConfig} from './cloud.js?v=20261009-r5';
import {importFile, recoverOriginal} from './migration.js?v=20261009-r5';
import {initializeProfile, profileId, switchProfile, persistProfile, profileCopy, PROFILE_KEY} from './profile.js?v=20261009-r5';

const $ = selector => document.querySelector(selector);
const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const safeURL = value => { try { const url = new URL(value); return ['https:','http:'].includes(url.protocol) ? url.href : ''; } catch { return ''; } };
const CATEGORIES = ['BAUER / APM','KAITECH / BIM','German','English & communication','Excel & automation','Fitness & recovery','Mind & capacity','Finance & purchases','Books, history & economy','Decisions','Saved insights','Ideas for later','Communication & logic'];
// Area shortcuts have stable topics; labels can change without rewriting user records.
const DEFAULT_AREAS = [...document.querySelectorAll('.area-links [data-action="area"]')].map((button,index)=>({id:`main-area-${index}`,kind:'main-area',title:button.querySelector('span').textContent,topic:button.dataset.id,topicLabel:button.dataset.id,icon:String(index),visible:true,order:index}));
const AREA_ICONS = [...document.querySelectorAll('.area-links [data-action="area"] svg')].map(svg=>svg.outerHTML);
const AREA_ICON_NAMES = ['Construction','Buildings','Fitness','Languages','Learning','Finance'];
function mainAreas(){
  const defaults=DEFAULT_AREAS.map(area=>({...area,...(state.settings[area.id]?.kind==='main-area'&&!state.settings[area.id].deleted?state.settings[area.id]:{})}));
  return [...defaults,...records(state,'settings').filter(r=>r.kind==='main-area'&&!DEFAULT_AREAS.some(area=>area.id===r.id))].sort((a,b)=>(a.order||0)-(b.order||0)||a.id.localeCompare(b.id));
}
function areaTopics(){return [...new Set([...CATEGORIES,...mainAreas().map(area=>area.topic),...records(state,'notes').map(note=>note.category)])];}
function topicLabel(topic){return mainAreas().find(area=>area.topic===topic)?.topicLabel||topic;}
function renderAreas(){
  document.querySelectorAll('.area-links [data-action="area"]').forEach(button=>button.remove());
  $('.area-links [data-action="calendar"]').insertAdjacentHTML('beforebegin',mainAreas().filter(area=>area.visible!==false).map(area=>`<button data-action="area" data-id="${esc(area.topic)}">${AREA_ICONS[area.icon]||AREA_ICONS[4]}<span>${esc(area.title)}</span></button>`).join(''));
}
function areasModal(){
  modal('Your main areas','Add, rename or remove shortcuts. Your notes, goals and history stay saved.',`<button class="button" data-action="edit-area">＋ Add area</button><div class="area-editor-list">${mainAreas().map(area=>`<div class="area-editor-row"><div><strong>${esc(area.title)}</strong><small>${area.visible===false?'Removed from sidebar':'Shown in sidebar'}</small></div><div class="area-editor-tools"><button class="button subtle" data-action="edit-area" data-id="${esc(area.id)}">Edit</button><button class="button ${area.visible===false?'soft':'ghost'}" data-action="toggle-area" data-id="${esc(area.id)}">${area.visible===false?'Restore':'Remove'}</button></div></div>`).join('')}</div><p>Removed areas remain here so you can restore them. Their resources are still available in Library.</p>`);
}
function areaModal(id){
  const area=mainAreas().find(a=>a.id===id);
  modal(area?'Edit area':'Add a main area','Choose a name you recognise. This is a shortcut, not another daily obligation.',`<form id="area-form"><input type="hidden" name="id" value="${esc(area?.id||'')}"><label for="area-title">Area name</label><input id="area-title" name="title" required maxlength="80" value="${esc(area?.title||'')}"><label for="area-icon">Icon</label><select id="area-icon" name="icon">${AREA_ICON_NAMES.map((name,index)=>`<option value="${index}" ${String(index)===(area?.icon||'4')?'selected':''}>${name}</option>`).join('')}</select>${actions('Save area')}</form>`);
}
const friendlyDate = date => new Date(`${date}T12:00:00`).toLocaleDateString(undefined, {month:'short',day:'numeric',year:'numeric'});
const taskHistoryDate = t => t.done && t.completedAt ? t.completedAt : t.date;
let boundProfile, device, state, startupMessage = '', storageError = false, recoveryLocked = false;
try {
  boundProfile=initializeProfile();
  device = localStorage.getItem('governor.device') || uid(); localStorage.setItem('governor.device', device);
  const saved = localStorage.getItem(STORAGE_KEY);
  if (saved) state = validateState(JSON.parse(saved));
  else if (localStorage.getItem('governor-data')) { state = importFile(localStorage.getItem('governor-data'), device); startupMessage = 'Your earlier Governor records were preserved and imported. The original device copy is untouched.'; }
  else state = initialState();
  // New reference cards never replace edited or archived user records.
  const references=initialState().notes;
  for(const id of ['german-practice','finance-purchases','recovery-baseline']) if(!state.notes[id]) state.notes[id]=references[id];
  persistProfile(state,boundProfile);
} catch (error) { state = initialState(); storageError = true; recoveryLocked = true; startupMessage = 'Device storage could not be read or saved. Export your existing device data from Settings before continuing; no original data was overwritten.'; }
let zone = ['tunnel','compass','vault'].includes(location.hash.slice(1)) ? location.hash.slice(1) : 'tunnel';
let query = '', category = 'All', showArchive = false, historyMonth = today().slice(0,7), lastToday = today(), undoAction;
let goalFilter='active', goalChartMetric='days', goalChartScope='current', chartPeriod='week', chartMonth=today().slice(0,7), calendarMonth=today().slice(0,7), routineWeek=addDays(today(),-((new Date(`${today()}T12:00:00`).getDay()+6)%7));
let timer = {duration:25, remaining:1500, end:0};
try { timer = {...timer, ...JSON.parse(localStorage.getItem('governor.timer') || '{}')}; } catch {}
const saveTimer = () => { try { localStorage.setItem('governor.timer', JSON.stringify(timer)); } catch {} };

function write(next, {sync = true, redraw = true} = {}) {
  if(recoveryLocked) throw new Error('Original storage needs recovery. Export it from Settings, then import a valid backup. Your original data has not been overwritten.');
  const checked = validateState(next);
  try { persistProfile(checked,boundProfile); }
  catch { storageError = true; throw new Error('Device storage is full or unavailable. Export a backup from Settings. This change was not saved.'); }
  state = checked; storageError = false;
  if (redraw) render();
  if (sync) cloud.schedule();
}
function edit(col, id, values, message = 'Saved', {undo = true, redraw = true} = {}) {
  const next = structuredClone(state), before = next[col][id] ? structuredClone(next[col][id]) : null;
  put(next, col, id, values, device); write(next, {redraw});
  if (undo) undoAction = () => {
    const restored = structuredClone(state);
    put(restored, col, id, before ? {...before,deleted:!!before.deleted} : {...values, deleted:true}, device); write(restored); toast('Change undone.');
  };
  if (message) toast(message, undo);
}
function changeGoal(id,values,message='Goal saved.') {
  const next=structuredClone(state), before=state.goals[id] ? structuredClone(state.goals[id]) : null;
  saveGoal(next,id,values,device);write(next);
  undoAction=()=>{const restored=structuredClone(state);saveGoal(restored,id,before?{...before,deleted:!!before.deleted,status:goalStatus(before)}:{deleted:true,status:'deleted',active:false},device);write(restored);toast('Goal change undone. History retained.');};
  toast(message,true);
}
function toast(message, undo = false) {
  const node = $('#toast'); node.innerHTML = `<span>${esc(message)}</span>${undo ? '<button type="button" data-action="undo">Undo</button>' : ''}`;
  node.classList.add('visible'); clearTimeout(toast.timeout); toast.timeout = setTimeout(() => node.classList.remove('visible'), undo ? 10000 : 5500);
}
const cloud = new CloudSync({onSessionChange:(user,config)=>{const nextId=profileId(user,config);if(nextId!==boundProfile){state=switchProfile(nextId);boundProfile=nextId;undoAction=null;timer={duration:25,remaining:1500,end:0};query='';render();}},getState:() => state, acceptState:incoming => {
  const merged = mergeStates(state, incoming);
  if (JSON.stringify(merged) !== JSON.stringify(state)) write(merged, {sync:false});
}, onStatus:(text, kind) => {const account=$('#account-button'),email=cloud.session?.user?.email;if(account)account.textContent=email?email.split(/[.@_]/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase():'♛'; $('#sync-status').textContent = text; $('#mobile-sync-status').textContent=text; $('#status-dot').className = `status-dot ${kind}`; $('#footer-status').textContent = text === 'Cloud up to date' ? 'Private cloud sync · up to date' : text; }});

function top(eyebrow, title, subtitle, aside = '') { return `<div class="page-heading"><div><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p class="subtitle">${subtitle}</p></div>${aside}</div>`; }
function goalName(id) { return state.goals[id]?.title || 'Personal priority'; }
function openToday() { return dailyTasks(state).filter(t => !t.done && !t.paused && !t.carriedTo); }
function visibleTasks() { return openToday().slice(0, taskLimit(state)); }
function taskHTML(task, index, done = false) {
  return `<article class="priority ${done ? 'done' : ''}"><button class="complete" data-action="complete" data-id="${esc(task.id)}" aria-label="${done ? 'Reopen' : 'Complete'} ${esc(task.title)}" aria-pressed="${!!task.done}">${done ? '✓' : ''}</button><span class="task-badge ${esc(task.goal)}">${esc(state.goals[task.goal]?.title || 'PERSONAL')}</span><div class="task-content"><p class="task-name">${esc(task.title)}</p><p class="task-action">${esc(task.action)}</p><div class="task-meta"><span class="category-dot ${esc(task.goal)}"></span>${esc(goalName(task.goal))}</div></div><div class="task-tools">${task.minutes?`<span class="task-duration">◷ ${esc(task.minutes)} min</span>`:''}${!done && index === 0 ? '<span class="primary-flag">PRIMARY</span>' : ''}<button class="icon-button" data-action="edit-task" data-id="${esc(task.id)}" aria-label="Edit ${esc(task.title)}">⋯</button></div></article>`;
}
function parkedLaneHTML() {
  const items=parkedTasks(state), locked=openToday().length>0;
  return `<section class="card parked-lane" aria-label="Parked priorities"><div class="section-head"><div><h2>Parked priorities <small>${items.length}</small></h2><p>Saved tasks for later · separate from thoughts and today’s progress.</p></div><button class="button soft" data-action="add-parked">＋ Add parked priority</button></div>${items.map(t=>`<article class="parked-priority" data-task-id="${esc(t.id)}"><div><strong>${esc(t.title)}</strong><p>${esc(t.action)}</p><small>Supports: ${esc(t.goal?goalName(t.goal):'Other')}</small></div><button class="icon-button" data-action="edit-task" data-id="${esc(t.id)}" aria-label="Edit parked ${esc(t.title)}">⋯</button></article>`).join('')||'<p class="empty">Have more than three things to do? Add the rest here. They stay safe until you choose them.</p>'}${items.length?`<p>${locked?'Finish your current priorities to unlock the next group.':'Your focus lane is clear. Choose up to '+taskLimit(state)+' from here, or stop for the day.'}</p><button class="button" data-action="parked" ${locked?'disabled':''}>Choose next priorities</button>`:''}</section>`;
}
function tunnel() {
  const tasks=visibleTasks(), primary=tasks[0], done=dailyTasks(state).filter(t=>t.done), mode=state.settings.mode?.value||'normal';
  const checkin=records(state,'checkins').find(x=>x.date===today()&&x.kind!=='routine'), total=tasks.length+done.length;
  return '<h1 class="sr-only">A clear path for today.</h1>'+
    (mode!=='normal'?`<div class="banner">${mode==='low'?'A lighter day is allowed. One small action is enough.':'Maintenance week: keep one useful action a day.'} Your other priorities are safely parked.</div>`:'')+
    `<div class="today-dashboard"><div class="today-layout"><div class="today-main"><section class="hero" aria-label="Primary mission"><div class="hero-content"><div class="eyebrow">MAIN FOCUS TODAY</div><h2>${esc(primary?goalName(primary.goal):done.length?'A useful step forward.':'Choose your next action.')}</h2><p class="hero-next">${esc(primary?.action || (done.length?'You can stop here, or choose another useful action.':'Make it small enough to begin.'))}</p><div class="hero-action"><button class="button focus-start" data-action="timer-toggle" id="timer-toggle">${timer.end?'Pause':'Start Focus Session'}</button><label class="sr-only" for="timer-duration">Focus length</label><select id="timer-duration" ${timer.end?'disabled':''}>${[10,25,45,50].map(n=>`<option value="${n}" ${timer.duration===n?'selected':''}>◷ ${n} min</option>`).join('')}</select></div><div class="hero-complete"><button class="button ghost" data-action="${primary?'complete':'add-task'}" ${primary?`data-id="${esc(primary.id)}"`:''}>${primary?'✓ Complete action':'＋ Choose my next action'}</button><span id="timer-display" class="timer-display">${timerText()}</span><button class="icon-button" data-action="timer-reset" aria-label="Reset focus timer">↺</button></div></div></section>
    <section class="card priorities-panel"><div class="section-head"><div><h2>TODAY’S PRIORITIES <small>${done.length} / ${total} completed</small></h2></div><button class="button subtle" data-action="add-task">＋ Add a priority</button></div><div class="priority-list">${tasks.map((t,i)=>taskHTML(t,i)).join('')||'<div class="empty">Choose a useful action when you’re ready.</div>'}</div><div class="quiet-row"><span>${tasks.length} of ${taskLimit(state)} in focus</span><button class="button ghost" data-action="add-parked">＋ Park a task</button><button class="button ghost" data-action="parked">View parked priorities →</button></div>${done.length?`<details><summary>${done.length} ${done.length===1?'action':'actions'} completed today</summary><div class="priority-list">${done.map(t=>taskHTML(t,0,true)).join('')}</div></details>`:''}</section></div>
    <aside class="today-side"><section class="card day-card"><h2>${new Date().toLocaleDateString(undefined,{weekday:'short',year:'numeric',month:'short',day:'numeric'})}</h2><label class="sr-only" for="energy-mode">Energy mode</label><select id="energy-mode"><option value="normal" ${mode==='normal'?'selected':''}>Normal day</option><option value="low" ${mode==='low'?'selected':''}>Low energy</option><option value="maintenance" ${mode==='maintenance'?'selected':''}>Maintenance week</option></select><div class="progress-line" role="progressbar" aria-label="Today's completed priorities" aria-valuemin="0" aria-valuemax="${Math.max(1,total)}" aria-valuenow="${done.length}"><span style="width:${total?100*done.length/total:0}%"></span></div><p>${done.length} / ${total} priorities completed</p></section>
    <section class="card quote-card"><p>“Small consistent actions<br>lead to big results.”</p></section>
    <section class="card quick-card"><p class="eyebrow">QUICK ACTIONS</p><div class="quick-grid"><button data-action="capture"><span aria-hidden="true"><svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="10"/><path d="M12 6v12M6 12h12"/></svg></span><strong>Capture Idea</strong><small>Task / note / link</small></button><button data-action="low-energy"><span aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M12 4C9 1 5 3 5 6 1 6 1 11 4 12 1 15 4 19 7 18 8 23 12 21 12 18V4ZM12 4c3-3 7-1 7 2 4 0 4 5 1 6 3 3 0 7-3 6-1 5-5 3-5 0M6 8l3 2M5 14l4-1M15 7l2 2M15 15l3-2"/></svg></span><strong>${mode==='low'?'Normal Day':'Low-Energy Mode'}</strong><small>Focus on essentials</small></button><button data-action="focus"><span aria-hidden="true"><svg viewBox="0 0 24 24"><circle cx="12" cy="14" r="8"/><path d="M12 9v5l3 2M9 2h6M12 2v4M18 5l2 2"/></svg></span><strong>Focus Timer</strong><small>One thing at a time</small></button><button data-action="checkin"><span aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M19 17A9 9 0 0 1 8 4a9 9 0 1 0 11 13Z"/></svg></span><strong>${checkin?'Day saved':'Finish Day'}</strong><small>Optional reflection</small></button></div></section></aside></div>${chartsHTML()}${parkedLaneHTML()}<section class="card dashboard-capture"><p class="eyebrow">CAPTURE & RETURN</p><form id="inline-capture" class="capture-inline"><label class="sr-only" for="capture-text">Capture a thought</label><input id="capture-text" name="text" placeholder="Save a quick thought…" maxlength="4000" required autocomplete="off"><button class="button" aria-label="Save thought">＋</button></form><button class="tiny-link" data-action="inbox">Your captured thoughts →</button></section></div>`;
}
function goalCard(g) {
  const progress=goalProgress(g), status=goalStatus(g), daily=planDayProgress(state,g);
  return `<article class="card goal-card" data-goal-id="${esc(g.id)}"><div class="section-head"><span class="note-tag">${esc(g.subtitle||'PERSONAL GOAL')}</span><span class="badge">${esc(status)}</span></div><h2>${esc(g.title)}</h2><p class="goal-outcome">${esc(g.outcome)}</p><div class="plan-day-summary"><strong>${daily.completed} / ${daily.days} days · ${daily.percent}%</strong><small>${esc(daily.horizon)} · ${friendlyDate(daily.start)} – ${friendlyDate(daily.end)}</small><span>Days with completed linked work</span></div>${g.deadline?`<p class="deadline">Target date · ${friendlyDate(g.deadline)}</p>`:''}<div class="progress-line" role="progressbar" aria-valuenow="${progress}" aria-valuemin="0" aria-valuemax="100" aria-label="${esc(g.title)} milestone progress"><span style="width:${progress}%"></span></div><div class="progress-meta"><span>${progress}%</span><span>${g.tracking==='target'?`${esc(g.current||0)} / ${esc(g.target||0)} ${esc(g.unit||'units')}`:g.tracking==='milestones'?'Completed milestones':'Your entered estimate'}</span></div>${g.evidence?`<p class="evidence">${esc(g.evidence)}</p>`:''}${g.nextAction?`<div class="goal-next"><span class="eyebrow">NEXT ACTION</span><p>${esc(g.nextAction)}</p>${status==='active'?`<button class="button ghost" data-action="goal-focus" data-id="${esc(g.id)}">Focus this action today →</button>`:''}</div>`:''}<div class="goal-actions"><button class="button soft" data-action="goal" data-id="${esc(g.id)}">Edit / progress</button><button class="button ghost" data-action="goal-history" data-id="${esc(g.id)}">History</button></div></article>`;
}
function chartsHTML() {
  const date=new Date(`${today()}T12:00:00`), monday=addDays(today(),-((date.getDay()+6)%7));
  const start=chartPeriod==='month'?`${chartMonth}-01`:monday;
  const count=chartPeriod==='month'?new Date(Number(chartMonth.slice(0,4)),Number(chartMonth.slice(5,7)),0).getDate():7;
  const days=executionDays(state,start,count), max=Math.max(1,...days.map(d=>d.count));
  return `<div class="charts-grid"><section class="card chart-card" data-chart="execution"><div class="section-head"><div><p class="eyebrow">ACTUAL SAVED COMPLETIONS</p><h2>${chartPeriod==='month'?'Monthly':'Weekly'} Execution</h2></div><label class="sr-only" for="chart-period">Execution period</label><select id="chart-period"><option value="week" ${chartPeriod==='week'?'selected':''}>This week</option><option value="month" ${chartPeriod==='month'?'selected':''}>Monthly</option></select></div>${chartPeriod==='month'?`<label class="sr-only" for="chart-month">Chart month</label><input id="chart-month" type="month" value="${chartMonth}">`:''}<p class="chart-total">${days.reduce((sum,d)=>sum+d.count,0)} actions completed · ${friendlyDate(start)} – ${friendlyDate(addDays(start,count-1))}</p><div class="chart-scroll"><div class="execution-bars ${chartPeriod==='month'?'monthly':''}" role="img" aria-label="Completed actions per day"><div class="bar-grid" style="--columns:${count}">${days.map(d=>`<div class="bar-column" data-date="${d.date}" data-count="${d.count}" title="${friendlyDate(d.date)}: ${d.count} completed actions"><span class="bar-value">${d.count}</span><div class="bar-track"><span class="execution-bar" style="height:${100*d.count/max}%"></span></div><span class="bar-label">${chartPeriod==='month'?Number(d.date.slice(-2)):new Date(`${d.date}T12:00:00`).toLocaleDateString(undefined,{weekday:'short'})}</span></div>`).join('')}</div></div></div><details class="chart-table"><summary>Read the values</summary><table><caption>Completed actions by date</caption><tbody>${days.map(d=>`<tr><th scope="row">${friendlyDate(d.date)}</th><td>${d.count}</td></tr>`).join('')}</tbody></table></details></section>
  <section class="card chart-card" data-chart="goals"><div class="section-head"><div><p class="eyebrow">YOUR PLANS · CONNECTED TO DAILY WORK</p><h2>Plans progress</h2></div><label class="sr-only" for="goal-chart-metric">Plan progress measure</label><select id="goal-chart-metric"><option value="days" ${goalChartMetric==='days'?'selected':''}>Days in horizon</option><option value="outcomes" ${goalChartMetric==='outcomes'?'selected':''}>Outcome targets</option></select></div><label class="sr-only" for="goal-chart-scope">Plans shown in chart</label><select id="goal-chart-scope"><option value="current" ${goalChartScope==='current'?'selected':''}>Active & paused plans</option><option value="all" ${goalChartScope==='all'?'selected':''}>All saved plans</option></select><p class="field-help">${goalChartMetric==='days'?'One day counts when at least one linked priority is completed. Each plan has its own horizon; Other only affects daily execution.':'Your saved milestones, measurable targets and entered estimates.'}</p><div class="goal-chart">${records(state,'goals').filter(g=>goalChartScope==='all'||['active','paused'].includes(goalStatus(g))).map(g=>{
    const daily=planDayProgress(state,g), progress=goalChartMetric==='days'?daily.percent:goalProgress(g);
    return `<div class="goal-chart-row" data-goal-id="${esc(g.id)}"><div><span>${esc(g.title)}</span><strong>${progress}%</strong></div><div class="progress-line" role="progressbar" aria-valuenow="${progress}" aria-valuemin="0" aria-valuemax="100" aria-label="${esc(g.title)} ${goalChartMetric==='days'?'daily':'outcome'} progress"><span style="width:${progress}%"></span></div><small>${goalChartMetric==='days'?`${daily.completed} / ${daily.days} days · ${esc(daily.horizon)} · ${esc(goalStatus(g))}<br>${friendlyDate(daily.start)} – ${friendlyDate(daily.end)}`:g.tracking==='target'?`${esc(g.current||0)} of ${esc(g.target||0)} ${esc(g.unit||'units')}`:g.tracking==='milestones'?'Based on checked monthly milestones':'Based on your entered estimate'}</small></div>`;
  }).join('')||'<p>No plans here. Add a plan in Plans when you are ready.</p>'}</div></section></div>`;
}
function calendarHTML() {
  const first=`${calendarMonth}-01`, firstDate=new Date(`${first}T12:00:00`), offset=(firstDate.getDay()+6)%7;
  const length=new Date(Number(calendarMonth.slice(0,4)),Number(calendarMonth.slice(5,7)),0).getDate();
  const days=Array.from({length:Math.ceil((length+offset)/7)*7},(_,i)=>addDays(first,i-offset));
  return `<section class="card calendar-card" id="calendar-section"><div class="section-head"><div><p class="eyebrow">PLAN WITH THE TIME YOU HAVE</p><h2>Calendar</h2><p>Tap a day to view or schedule an action.</p></div><label class="sr-only" for="calendar-month">Calendar month</label><input id="calendar-month" type="month" value="${calendarMonth}"></div><div class="calendar-weekdays" aria-hidden="true">${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(d=>`<span>${d}</span>`).join('')}</div><div class="calendar-grid">${days.map(day=>{
    const tasks=dailyTasks(state,day).filter(t=>!t.carriedTo), goals=records(state,'goals').filter(g=>g.deadline===day||[1,2,3].some(n=>g[`month${n}Date`]===day)), done=records(state,'tasks').filter(t=>t.done&&(t.completedAt||t.date)===day).length;
    const label=`${friendlyDate(day)}; ${tasks.length} scheduled actions; ${done} completed; ${goals.length} goal deadlines`;
    return `<button class="calendar-day ${day===today()?'today':''} ${day.slice(0,7)!==calendarMonth?'outside':''}" data-action="calendar-day" data-id="${day}" aria-label="${esc(label)}"><span>${Number(day.slice(-2))}</span><span class="calendar-dots">${tasks.length?'<i class="planned" aria-hidden="true"></i>':''}${done?'<i class="finished" aria-hidden="true"></i>':''}${goals.length?'<i class="target" aria-hidden="true"></i>':''}</span>${tasks[0]?`<small>${esc(tasks[0].title)}</small>`:goals[0]?`<small>${esc(goals[0].title)} · target</small>`:''}</button>`;
  }).join('')}</div><p class="calendar-key">● Scheduled action <span>● Completed</span> <em>● Goal target date</em></p></section>`;
}
function compass() {
  const plan=state.settings.plan, start=plan.start, end=plan.horizon||addDays(start,89), day=Math.max(1,dayDifference(today(),start)+1);
  const latest=records(state,'reviews').filter(r=>!r.archived).sort((a,b)=>b.date.localeCompare(a.date));
  const goals=records(state,'goals').filter(g=>goalFilter==='all'||goalStatus(g)===goalFilter);
  return top('PLANS · THE COMPASS','Direction, without the noise.','Three priorities by default. Other goals are optional.',`<button class="button subtle" data-action="plan">Edit horizon</button>`)+
    `<div class="banner"><div class="plan-meta"><strong>Your sprint · ${friendlyDate(start)} – ${friendlyDate(end)}</strong><span>${day>dayDifference(end,start)+1?'Review and set your next chapter when ready.':`Day ${day} of your current plan`}</span></div>${plan.military?`Military planning date: ${friendlyDate(plan.military)}. Adjust this whenever the timeline changes.`:'Military timing uncertain? Keep the date open and work with the horizon you know.'}</div>
    <div class="section-head"><div><h2>Your outcomes</h2><p>BAUER, KAITECH and capacity first. Supporting skills stay optional.</p></div><button class="button" data-action="add-goal">＋ Add goal</button></div><div class="goal-filters"><label class="sr-only" for="goal-filter">Goal status</label><select id="goal-filter">${['active','paused','completed','archived','all'].map(v=>`<option value="${v}" ${goalFilter===v?'selected':''}>${v==='all'?'All saved goals':v[0].toUpperCase()+v.slice(1)+' goals'}</option>`).join('')}</select><button class="button ghost" data-action="deleted-goals">Deleted goal history</button></div><div class="goal-grid">${goals.map(goalCard).join('')||'<div class="empty">No goals in this section. Your other goals and their history remain saved.</div>'}</div>
    ${chartsHTML()}${calendarHTML()}${routinesHTML()}
    <div class="section-stack"><section class="card"><div class="section-head"><div><p class="eyebrow">15 MINUTES · ONCE A WEEK</p><h2>Reflect. Adjust. Move on.</h2><p>${latest[0]?`Last review: ${friendlyDate(latest[0].date)}`:'Start with this week. No catch-up required.'}</p></div><button class="button" data-action="weekly">Start weekly review →</button><button class="button ghost" data-action="monthly">Monthly review</button></div><p>5 minutes: what moved? 5 minutes: what got in the way? 5 minutes: what will change?</p><details><summary>Past reviews</summary>${latest.map(r=>`<article class="review-entry"><div class="section-head"><h3>${r.period==='month'?'Monthly':'Weekly'} · ${friendlyDate(r.date)}</h3><button class="button ghost" data-action="weekly" data-id="${esc(r.id)}">Edit</button><button class="button ghost" data-action="delete-review" data-id="${esc(r.id)}">Delete</button></div><p><strong>Progress:</strong> ${esc(r.wins)}<br><strong>Lessons:</strong> ${esc(r.obstacles)}<br><strong>Next adjustment:</strong> ${esc(r.next)}</p></article>`).join('')||'<p>Your first review will appear here.</p>'}</details></section>
    <section class="card"><details><summary>Your optional 1-, 3- and 5-year direction</summary><button class="button ghost" data-action="why">Edit your Why →</button><div class="why-grid">${plan.values?`<p class="values-note"><strong>Your values:</strong> ${esc(plan.values)}</p>`:''}${[1,3,5].map(n=>`<div><h3>${n} ${n===1?'year':'years'}</h3><p>${esc(plan[`why${n}`]||'What would make this chapter meaningful for you?')}</p></div>`).join('')}</div></details></section>
    <section class="card"><p class="eyebrow">YOUR RECORD ACROSS MONTHS</p><h2>Monthly history</h2><p>Actions and check-ins stay saved. Missed days simply stay blank.</p><div class="history-filters"><label class="sr-only" for="history-month">Choose month</label><input type="month" id="history-month" value="${historyMonth}"><button class="button subtle" data-action="history-export">Export this month</button></div><div id="month-history">${historyHTML()}</div></section></div>`;
}
function historyHTML() {
  const tasks = records(state,'tasks').filter(t=>taskHistoryDate(t).startsWith(historyMonth));
  const logs = records(state,'checkins').filter(c=>c.kind!=='routine'&&c.date.startsWith(historyMonth));
  const dates = [...new Set([...tasks.map(taskHistoryDate),...logs.map(x=>x.date)])].sort().reverse();
  return `<p class="history-count">${tasks.filter(t=>t.done).length} completed actions · ${logs.length} check-ins</p>${dates.map(date=>`<div class="history-day"><h3>${friendlyDate(date)}</h3>${tasks.filter(t=>taskHistoryDate(t)===date).map(t=>`<p><span class="${t.done?'done-label':'archived-label'}">${t.done?'✓ Completed':t.paused?'Parked':'Planned'}</span> · ${esc(t.title)}</p>`).join('')}${logs.filter(c=>c.date===date).map(c=>`<p>${esc(c.energy)} · ${esc(c.note)}</p>`).join('')}</div>`).join('') || '<p>No entries this month. Your saved months remain available in the selector.</p>'}`;
}
function noteHTML(note) {
  const url=safeURL(note.url), book=note.entryType==='book', routine=note.entryType==='routine';
  const percent=note.pagesTotal>0?Math.min(100,Math.round(100*(note.pagesRead||0)/note.pagesTotal)):null;
  return `<article class="card note-card"><div class="note-tag">${esc(topicLabel(note.category)).toUpperCase()}${note.archived?' · ARCHIVED':''}</div><h2>${esc(note.title)}</h2>${book?`<p class="book-meta">${esc(note.author||'')} · ${esc(note.readingStatus||'To read')}</p>${percent===null?`<small>${note.readingProgress!=null?`${esc(note.readingProgress)}% entered in your imported book`:'Pages not tracked yet.'}</small>`:`<div class="progress-line"><span style="width:${percent}%"></span></div><p>${esc(note.pagesRead||0)} / ${esc(note.pagesTotal)} pages · ${percent}%</p>`}`:routine?`<p class="book-meta">Optional routine · ${esc(note.routineTarget||1)} times / week</p>`:''}<p>${esc(note.body)}</p>${note.tags?`<p class="note-tags">${esc(note.tags)}</p>`:''}${note.goal?`<small>Supports: ${esc(goalName(note.goal))}</small>`:''}<div class="note-actions">${url?`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">Open resource ↗</a>`:'<span></span>'}<button class="button ghost" data-action="note" data-id="${esc(note.id)}">Edit →</button><button class="button ghost" data-action="note-task" data-id="${esc(note.id)}">Make priority</button></div></article>`;
}
function vaultNotes() {return records(state,'notes').filter(n=>showArchive?n.archived:!n.archived).filter(n=>category==='All'||n.category===category).filter(n=>`${n.title} ${n.body} ${n.category} ${topicLabel(n.category)} ${n.author||''} ${n.tags||''}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>b.updatedAt-a.updatedAt);}
function groupedNotes() {
  const notes=vaultNotes(), groups=[...new Set(notes.map(n=>n.category))];
  return groups.map(c=>`<section class="library-group"><h2 class="library-heading">${esc(topicLabel(c))} <small>${notes.filter(n=>n.category===c).length}</small></h2><div class="note-grid">${notes.filter(n=>n.category===c).map(noteHTML).join('')}</div></section>`).join('')||'<div class="empty">No matching resources. Save one useful thing when you find it.</div>';
}
function vault() {
  return top('LIBRARY · THE VAULT','Keep the useful things close.','Your knowledge, books, decisions and ideas. No extra daily task list.')+
  `<div class="vault-toolbar"><label class="sr-only" for="vault-search">Search the Vault</label><input id="vault-search" type="search" placeholder="Search a topic, note, book or idea…" value="${esc(query)}"><label class="sr-only" for="vault-category">Filter by topic</label><select id="vault-category">${['All',...areaTopics()].map(c=>`<option value="${esc(c)}" ${category===c?'selected':''}>${esc(c==='All'?c:topicLabel(c))}</option>`).join('')}</select><button class="button" data-action="note">＋ Save a note</button></div><div class="library-actions"><button class="button soft" data-action="book">＋ Add book</button><button class="button soft" data-action="routine">＋ Optional routine</button><button class="button ghost" data-action="vault-archive">${showArchive?'Show active resources':'View archived resources'}</button></div><div id="note-grid">${groupedNotes()}</div>
  <section class="card"><div class="section-head"><div><h2>Your thought inbox</h2><p>Capture now. Decide later.</p></div><button class="button ghost" data-action="inbox">Open inbox →</button></div><p>${records(state,'captures').filter(c=>!c.archived).length} thoughts saved. They do not become tasks automatically.</p></section>
  ${records(state,'legacy').some(l=>l.kind!=='goal-history')?`<section class="card"><h2>Your preserved Governor records</h2><p>Original projects, goals, habits, books and other categories are still here, including their original fields in backups.</p><button class="button soft" data-action="legacy">Browse preserved records →</button></section>`:''}`;
}
function routinesHTML() {
  const routines=records(state,'notes').filter(n=>n.entryType==='routine'&&!n.archived), days=Array.from({length:7},(_,i)=>addDays(routineWeek,i));
  return `<section class="card routines-card"><details><summary>Optional routines · no streaks or penalties</summary><p>Only track routines that help you. Blank days are allowed. These do not become Today priorities.</p><div class="section-head"><label for="routine-week">Week starting</label><input type="date" id="routine-week" value="${routineWeek}"><button class="button soft" data-action="routine">＋ Add routine</button></div>${routines.map(n=>{const completed=days.filter(d=>state.checkins[`routine-${n.id}-${d}`]?.done).length;return `<article class="routine-row"><div class="section-head"><h3>${esc(n.title)}</h3><span>${completed} / ${n.routineTarget||1} this week</span><button class="button ghost" data-action="note" data-id="${esc(n.id)}">Edit</button></div><div class="routine-days">${days.map(d=>{const done=!!state.checkins[`routine-${n.id}-${d}`]?.done;return `<button data-action="routine-toggle" data-id="${esc(n.id)}" data-date="${d}" aria-pressed="${done}" aria-label="${esc(n.title)} · ${friendlyDate(d)}" ${d>today()?'disabled':''}>${new Date(`${d}T12:00:00`).toLocaleDateString(undefined,{weekday:'short'})}<strong>${done?'✓':Number(d.slice(-2))}</strong></button>`;}).join('')}</div></article>`;}).join('')||'<p>No routines added. You can leave this empty.</p>'}</details></section>`;
}
function searchModal(value='') {
  const q=value.trim().toLowerCase();
  const matches=q?['tasks','goals','notes','captures'].flatMap(col=>records(state,col).filter(r=>`${r.title||r.text||''} ${r.action||r.body||r.outcome||''} ${r.tags||''}`.toLowerCase().includes(q)).map(r=>({col,r}))).slice(0,40):[];
  modal('Find anything in your Governor','Search saved actions, goals, notes and thoughts.',`<form id="search-form"><label class="sr-only" for="search-everything">Search everything</label><input id="search-everything" name="query" type="search" value="${esc(value)}" placeholder="A task, goal, book or idea…"><button class="button" type="submit">Search</button></form><ul class="search-results">${matches.map(({col,r})=>`<li><span>${esc(col)}${r.archived?' · archived':''}</span><button class="button ghost" data-action="${{tasks:'edit-task',goals:'goal',notes:'note',captures:'capture-note'}[col]}" data-id="${esc(r.id)}">${esc(r.title||r.text)}</button></li>`).join('')||`<li>${q?'No matching records.':'Enter a word to find your saved records.'}</li>`}</ul>`);
}
function render() {
  const account=$('#account-button');if(account){const email=cloud.session?.user?.email;account.textContent=email?email.split(/[.@_]/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase():'♛';account.setAttribute('aria-label',email?`Account: ${email}`:'Account and sign in');}
  renderAreas();
  document.body.dataset.currentZone=zone;
  $('#header-date').textContent=new Date().toLocaleDateString(undefined,{weekday:'short',day:'numeric',month:'short',year:'numeric'});
  const scroll = window.scrollY;
  $('#main').innerHTML = (storageError ? `<div class="banner" role="alert">Device storage needs attention. Changes are not safe until storage works. <button class="button subtle" data-action="settings">Export / restore data</button></div>` : '') + ({tunnel,compass,vault})[zone]();
  document.querySelectorAll('[data-zone]').forEach(a=>{a.classList.toggle('active',a.dataset.zone===zone); if(a.dataset.zone===zone)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});
  if(zone==='tunnel') { try { $('#capture-text').value = localStorage.getItem('governor.capture.draft') || ''; } catch {} }
  window.scrollTo(0,scroll);
}
let focusReturn;
function modal(title, subtitle, body) {
  focusReturn = document.activeElement;
  $('#modal-content').innerHTML = `<div class="modal-head"><h2 id="modal-title">${title}</h2><button type="button" class="icon-button" data-action="close" aria-label="Close dialog">×</button></div>${subtitle ? `<p class="modal-subtitle">${subtitle}</p>` : ''}${body}`;
  if (!$('#modal').open) $('#modal').showModal();
  const first = $('#modal-content input:not([type=hidden]), #modal-content textarea'); if(first) first.focus();
}
function closeModal() { $('#modal').close(); if(focusReturn?.isConnected) focusReturn.focus(); }
function actions(text='Save', extra='') { return `<p id="form-error" class="form-error" role="alert"></p><div class="modal-actions">${extra}<button type="button" class="button subtle" data-action="close">Cancel</button><button class="button" type="submit">${text}</button></div>`; }
function taskModal(id, date=today(), fromCapture='', parked=false) {
  const task=id?state.tasks[id]:null, selected=task?.date||date, capture=state.captures[fromCapture];
  const limit=selected===today()?taskLimit(state):3;
  if(!task && !parked && dailyTasks(state,selected).filter(t=>!t.done&&!t.paused&&!t.carriedTo).length>=limit){toast(`Keep ${limit} in focus. Park or complete an action before adding another.`);return;}
  const options=records(state,'goals');if(task?.goal&&!options.some(g=>g.id===task.goal)&&state.goals[task.goal])options.push(state.goals[task.goal]);
  modal(task?'Edit your priority':parked?'Add a parked priority':'One priority. One next action.','Use a verb and a real output. Change the schedule date to carry an action forward without losing its earlier record.',`<form id="task-form"><input type="hidden" name="parked" value="${parked||task?.paused?'1':''}"><input type="hidden" name="id" value="${esc(id||'')}"><input type="hidden" name="capture" value="${esc(fromCapture)}"><label for="task-title">Priority</label><input id="task-title" name="title" value="${esc(task?.title||(capture?.sourceTitle||capture?.text.split('\n')[0])?.slice(0,160)||'')}" placeholder="Finish the KAITECH data map" required maxlength="160"><label for="task-action">The next concrete action</label><textarea id="task-action" name="action" placeholder="Check the source IDs against the schema" maxlength="1000">${esc(task?.action||capture?.text.slice(0,1000)||'')}</textarea><div class="form-row"><div><label for="task-date">Schedule date</label><input id="task-date" name="date" type="date" required value="${selected}"></div><div><label for="task-goal">Supports</label><select id="task-goal" name="goal"><option value="" ${!task?.goal?'selected':''}>Other · not connected to a plan</option>${options.map(g=>`<option value="${esc(g.id)}" ${task?.goal===g.id?'selected':''}>${esc(g.title)} · ${esc(g.horizon||'90 days')} · ${esc(goalStatus(g))}</option>`).join('')}</select></div></div><label for="task-minutes">Estimated minutes · optional</label><input id="task-minutes" name="minutes" type="number" min="0" max="1440" value="${task?.minutes||0}">${actions(parked?'Save parked priority':'Save priority',task?`<button type="button" class="button ghost" data-action="park-task" data-id="${esc(id)}">Park for later</button><button type="button" class="button soft" data-action="primary" data-id="${esc(id)}">Make primary</button><button type="button" class="button danger" data-action="delete-task" data-id="${esc(id)}">Delete action</button>`:'')}</form>`);
}
function captureModal(id) {
  const captured=state.captures[id];
  modal('Park the thought.', 'You don’t need to solve it now. Your current work stays where you left it.', `<form id="capture-form"><input type="hidden" name="id" value="${esc(id||'')}"><label class="sr-only" for="modal-capture">Thought or idea</label><textarea id="modal-capture" name="text" placeholder="What’s on your mind?" required maxlength="4000">${esc(captured?.text||localStorage.getItem('governor.capture.draft')||'')}</textarea>${actions('Capture & return',captured?`<button type="button" class="button danger" data-action="delete-capture" data-id="${esc(id)}">Delete thought</button>`:'')}</form>`);
}
function inboxModal(showUndo=false) {
  const inbox = records(state,'captures').filter(c=>!c.archived).sort((a,b)=>b.updatedAt-a.updatedAt);
  modal('Your thought inbox', 'Keep useful ideas. Park the rest without making another obligation.', ` ${showUndo?'<p>Thought deleted. <button class="button soft" data-action="undo">Undo deletion</button></p>':''}<ul class="capture-list">${inbox.map(c=>`<li><div style="flex:1;min-width:0"><p>${esc(c.text)}</p><time>${friendlyDate(c.date)}</time></div><button class="button soft" data-action="capture-task" data-id="${esc(c.id)}">Make priority</button><button class="button ghost" data-action="edit-capture" data-id="${esc(c.id)}">Edit</button><button class="button ghost" data-action="capture-note" data-id="${esc(c.id)}">Keep in Vault</button><button class="icon-button" data-action="archive-capture" data-id="${esc(c.id)}" aria-label="Archive thought">✓</button><button class="button danger" data-action="delete-capture" data-id="${esc(c.id)}">Delete</button></li>`).join('')||'<li><p>Your inbox is clear.</p></li>'}</ul><details><summary>Archived thoughts</summary><ul class="capture-list">${records(state,'captures').filter(c=>c.archived).map(c=>`<li><p>${esc(c.text)}</p><button class="button ghost" data-action="restore-capture" data-id="${esc(c.id)}">Restore</button><button class="button danger" data-action="delete-capture" data-id="${esc(c.id)}">Delete</button></li>`).join('')||'<p>Nothing archived.</p>'}</ul></details>`);
}
function parkedModal() {
  const items=parkedTasks(state), locked=openToday().length>0;
  modal('Your parked priorities',locked?'Finish your current priorities before starting the next group. You can add and edit parked tasks now.':'Choose up to '+taskLimit(state)+' priorities for your next group. You can stop for the day instead.',`<button class="button soft" data-action="add-parked">＋ Add parked priority</button><form id="parked-focus-form"><ul class="capture-list">${items.map(t=>`<li><label class="parked-select"><input type="checkbox" name="tasks" value="${esc(t.id)}" ${locked?'disabled':''}><span><strong>${esc(t.title)}</strong><br>${esc(t.action)}<br><small>Supports: ${esc(t.goal?goalName(t.goal):'Other')}</small></span></label><button type="button" class="icon-button" data-action="edit-task" data-id="${esc(t.id)}" aria-label="Edit parked ${esc(t.title)}">⋯</button></li>`).join('')||'<li><p>No parked priorities. Use Add parked priority for your extra tasks.</p></li>'}</ul><p id="form-error" class="form-error" role="alert"></p><div class="modal-actions"><button type="button" class="button subtle" data-action="close">Close</button><button class="button" ${locked||!items.length?'disabled':''}>Focus selected priorities</button></div></form>`);
}

function checkinModal() {
  const c = records(state,'checkins').find(x=>x.date===today()&&x.kind!=='routine');
  modal('Close the day gently.', 'One sentence is enough. You can skip this whenever it doesn’t help.', `<form id="checkin-form"><input type="hidden" name="id" value="${esc(c?.id||today())}"><label>How was your capacity today?</label><div class="checkin-choice">${['low','okay','good'].map(v=>`<label><input type="radio" name="energy" value="${v}" ${(c?.energy||'okay')===v?'checked':''}>${v}</label>`).join('')}</div><label for="checkin-note">One useful step or tomorrow’s adjustment</label><textarea id="checkin-note" name="note" maxlength="4000" placeholder="Finished the data checks. Tomorrow I’ll start with the report.">${esc(c?.note||'')}</textarea>${actions('Save check-in')}</form>`);
}
function weeklyModal(id, period='week') {
  const review = id ? state.reviews[id] : records(state,'reviews').find(r=>r.date===today()&&(r.period||'week')===period);
  period=review?.period||period;
  const done = records(state,'tasks').filter(t=>t.done && taskHistoryDate(t)>=(period==='month'?today().slice(0,7)+'-01':addDays(today(),-6)) && taskHistoryDate(t)<=today());
  const suggested = done.map(t=>`• ${t.title}`).join('\n');
  modal(period==='month'?'Your monthly review':'Your 15-minute weekly review', 'Adjust the system to real life. There is no missing-week backlog.', `<form id="weekly-form"><input type="hidden" name="period" value="${period}"><input type="hidden" name="id" value="${esc(review?.id||'')}"><div class="review-prompt"><h3>1. What actually moved? · 5 min</h3><p>Look at evidence for BAUER, KAITECH and your capacity. ${done.length} actions completed this ${period}.</p></div><label for="weekly-wins">Progress and evidence</label><textarea id="weekly-wins" name="wins" required maxlength="6000" placeholder="A report, a checked dataset, more sustainable sleep…">${esc(review?.wins||suggested)}</textarea><label for="weekly-obstacles">2. What got in the way? · 5 min</label><textarea id="weekly-obstacles" name="obstacles" maxlength="6000" placeholder="What made action harder? What could you simplify?">${esc(review?.obstacles||'')}</textarea><label for="weekly-next">3. What will you change next ${period}? · 5 min</label><textarea id="weekly-next" name="next" maxlength="6000" placeholder="One adjustment for each active outcome. Consider a maintenance week when needed.">${esc(review?.next||'')}</textarea>${actions('Save review')}</form>`);
}
function goalModal(id) {
  const g=id?state.goals[id]:null, status=g?goalStatus(g):'paused';
  modal(g?'Edit goal and progress':'Create a concrete goal','Start with a real outcome. New goals are saved for later unless you choose to activate them.',`<form id="goal-form"><input type="hidden" name="id" value="${esc(id||'')}"><label for="goal-title">Goal name</label><input id="goal-title" name="title" value="${esc(g?.title||'')}" maxlength="120" required><label for="goal-subtitle">Area / project</label><input id="goal-subtitle" name="subtitle" value="${esc(g?.subtitle||'')}" maxlength="160" placeholder="BAUER / BIM / Fitness / German"><label for="goal-outcome">Outcome / description</label><textarea id="goal-outcome" name="outcome" maxlength="2000" required placeholder="What concrete result will exist?">${esc(g?.outcome||'')}</textarea><div class="form-row"><div><label for="goal-status">Status</label><select id="goal-status" name="status">${['active','paused','completed','archived'].map(v=>`<option value="${v}" ${status===v?'selected':''}>${v[0].toUpperCase()+v.slice(1)}</option>`).join('')}</select></div><div><label for="goal-deadline">Target date · optional</label><input type="date" id="goal-deadline" name="deadline" value="${esc(g?.deadline||'')}"></div></div><label for="goal-horizon">Goal horizon</label><select id="goal-horizon" name="horizon">${['30 days','90 days','1 year','3 years','5+ years'].map(v=>`<option ${(g?.horizon||'90 days')===v?'selected':''}>${v}</option>`).join('')}</select><label for="goal-start">Plan start date</label><input id="goal-start" name="startDate" type="date" required value="${g?planWindow(state,g).start:today()}"><p class="field-help">Daily progress counts one day when you complete at least one priority linked to this plan. Its horizon starts here; blank days have no penalty.</p><label for="goal-next">Next concrete action · optional</label><textarea id="goal-next" name="nextAction" maxlength="1000" placeholder="Update the planned and actual quantities in the site report.">${esc(g?.nextAction||'')}</textarea>
  <details open><summary>Progress and measurable target</summary><label for="goal-tracking">Measure progress using</label><select id="goal-tracking" name="tracking"><option value="manual" ${(g?.tracking||'manual')==='manual'?'selected':''}>An explicitly entered percentage</option><option value="target" ${g?.tracking==='target'?'selected':''}>A measurable target</option><option value="milestones" ${g?.tracking==='milestones'?'selected':''}>Completed monthly milestones</option></select><div id="manual-fields" ${g?.tracking&&g.tracking!=='manual'?'hidden':''}><label for="goal-progress">Your progress estimate · 0–100%</label><input type="number" id="goal-progress" name="progress" min="0" max="100" required value="${g?.progress??0}"></div><div id="target-fields" ${g?.tracking!=='target'?'hidden':''}><div class="form-row"><div><label for="goal-current">Achieved so far</label><input type="number" id="goal-current" name="current" min="0" step="any" value="${g?.current??0}"></div><div><label for="goal-target">Target</label><input type="number" id="goal-target" name="target" min="0" step="any" value="${g?.target??0}"></div></div><label for="goal-unit">Unit</label><input id="goal-unit" name="unit" maxlength="80" placeholder="deliverables / sessions / EGP" value="${esc(g?.unit||'')}"></div><label for="goal-evidence">Evidence / latest update</label><textarea id="goal-evidence" name="evidence" maxlength="3000" placeholder="A finished report, checked dataset or observed change.">${esc(g?.evidence||'')}</textarea></details>
  <details><summary>Monthly milestones</summary>${[1,2,3].map(n=>`<label for="goal-month-${n}">Month ${n}</label><input id="goal-month-${n}" name="month${n}" maxlength="500" value="${esc(g?.[`month${n}`]||'')}" placeholder="One concrete output for this month"><div class="form-row"><div><label for="milestone-date-${n}">Target date · optional</label><input id="milestone-date-${n}" name="month${n}Date" type="date" value="${esc(g?.[`month${n}Date`]||'')}"></div><div><label for="milestone-evidence-${n}">Evidence · optional</label><input id="milestone-evidence-${n}" name="month${n}Evidence" maxlength="1000" value="${esc(g?.[`month${n}Evidence`]||'')}"></div></div><label class="checkbox-label"><input type="checkbox" name="month${n}Done" ${g?.[`month${n}Done`]?'checked':''}> Completed this milestone</label>`).join('')}<label for="goal-milestone">Earlier milestone notes / additional context</label><textarea id="goal-milestone" name="milestone" maxlength="3000">${esc(g?.milestone||'')}</textarea></details>${actions(g?'Save milestone':'Create goal',g?`<button class="button danger" type="button" data-action="delete-goal" data-id="${esc(g.id)}">Delete goal</button>`:'')}</form>`);
}
function goalHistoryModal(id) {
  const goal=state.goals[id], revisions=goalHistory(state,id);
  modal(`${goal?.title||'Goal'} · history`,'Changing or deleting a goal keeps its earlier versions and completed action records.',`<div class="goal-history">${revisions.map(g=>`<details class="review-entry"><summary>${g.updatedAt?new Date(g.updatedAt).toLocaleDateString():'Original saved version'} · ${esc(g.title)} · ${esc(goalStatus(g))} · ${goalProgress(g)}%</summary><p>${esc(g.outcome)}</p><p>${esc(g.evidence||'No evidence note entered.')}</p><p>${esc(g.milestone||'')}</p>${[1,2,3].filter(n=>g[`month${n}`]).map(n=>`<p>Month ${n}: ${g[`month${n}Done`]?'✓ ':''}${esc(g[`month${n}`])}</p>`).join('')}</details>`).join('')||'<p>Earlier versions will appear after your first goal update. Your existing goal is unchanged.</p>'}</div><details><summary>Linked completed actions</summary>${records(state,'tasks').filter(t=>t.goal===id&&t.done).map(t=>`<p>✓ ${esc(t.title)} · ${friendlyDate(t.completedAt||t.date)}</p>`).join('')||'<p>No completed actions yet.</p>'}</details>`);
}
function deletedGoalsModal() {
  modal('Deleted goal history','Deletion hides a goal from your plans. Its historical versions, linked actions and backup records remain available.',Object.values(state.goals).filter(g=>g.deleted).map(g=>`<article class="review-entry"><h3>${esc(g.title)}</h3><button class="button soft" data-action="goal-history" data-id="${esc(g.id)}">View history</button></article>`).join('')||'<p>No deleted goals.</p>');
}
function calendarDayModal(date) {
  const tasks=dailyTasks(state,date).filter(t=>!t.carriedTo), goals=records(state,'goals').filter(g=>g.deadline===date||[1,2,3].some(n=>g[`month${n}Date`]===date));
  modal(friendlyDate(date),'Scheduled actions stay saved until you choose to change them.',`<div class="priority-list">${tasks.map((t,i)=>taskHTML(t,i,t.done)).join('')||'<p>No actions scheduled for this day.</p>'}</div>${goals.length?`<h3 style="margin-top:20px">Goal and milestone target dates</h3>${goals.map(g=>`<p>${esc(g.title)} <button class="button ghost" data-action="goal" data-id="${esc(g.id)}">Edit goal</button></p>`).join('')}`:''}<button class="button" style="margin-top:20px" data-action="calendar-add" data-id="${date}">＋ Schedule an action</button>`);
}
function guideModal() {
  modal('Your two-minute Governor guide','One place to add, track and own your progress.',`<ol class="manual-steps"><li><strong>Morning · Today:</strong> Read the gold primary action. Tap Complete when finished. Use the dots to edit, park or schedule an action. Keep three in focus. Put any extra tasks in the Parked priorities lane using Add parked priority. Finish your current group, then Choose next priorities selects up to three more. Parked tasks have Supports too and count only after completion. Low energy shows just one.</li><li><strong>Capture:</strong> Save a distraction in one line and return to work. In the inbox, keep it as a Library note, turn it into a priority or delete it with undo.</li><li><strong>Goals · Plans:</strong> Add a goal, give it an outcome and next action, and choose active or paused. Edit progress using your estimate, a measurable target, or checked monthly milestones. Choose completed or archived when appropriate. Filter to find old goals and reactivate them. History retains earlier versions.</li><li><strong>Progress & calendar:</strong> The execution chart counts real completed actions. Choose a saved plan under Supports when editing a priority, or Other to leave it unlinked. The Plans chart counts distinct days with completed linked work divided by that plan’s 30-day, 90-day or yearly horizon. Set the plan start date in Edit / progress. Several tasks on one day count once. Outcome targets keeps your milestone and manual measurements available. Tap a calendar day to schedule an action; changing its date preserves the earlier record.</li><li><strong>Weekly:</strong> Spend about 15 minutes on what moved, what blocked you, and one or two corrections. Monthly reviews and your values/1-, 3-, 5-year direction are optional.</li><li><strong>Library:</strong> Search by category. Use Settings → Manage areas to add, rename, remove or restore your sidebar shortcuts; saved records stay in place. Add notes, books or optional routines; archive them when finished. German, English, finance and reading create no daily obligation.</li><li><strong>Saving:</strong> Changes save immediately on this browser. Cloud up to date means synced; pending means the local copy is safe but not uploaded yet. Use the same login and app link on phone and laptop. Offline changes merge on reconnection.</li><li><strong>Backups & privacy:</strong> Settings → Export backup saves a JSON file. Import backup merges records and exports the current copy first. Keep backups before a long absence. Signing out opens a separate local workspace; signing back in restores your account. Saved browser copies are not encrypted. Use your own locked device.</li></ol>`);
}
function planModal(whyOnly=false) {
  const p = state.settings.plan;
  modal(whyOnly?'Your reasons. Your own pace.':'Plan with the time you know.',whyOnly?'These are your reasons, not someone else’s success criteria.':'A 90-day sprint is a guide. Change the horizon when military timing becomes clearer.', `<form id="plan-form">${whyOnly ? `<label for="core-values">Your core values · optional</label><textarea id="core-values" name="values" maxlength="4000" placeholder="Autonomy, competence, capacity, stability — in your own words">${esc(p.values||'')}</textarea>`+[1,3,5].map(n=>`<label for="why-${n}">${n}-year Why</label><textarea id="why-${n}" name="why${n}" maxlength="4000" placeholder="What do I want, and why does it matter to me?">${esc(p[`why${n}`])}</textarea>`).join('') : `<label for="plan-start">Sprint start</label><input id="plan-start" name="start" type="date" required value="${esc(p.start)}"><label for="plan-end">Planning horizon <small>optional; defaults to 90 days</small></label><input id="plan-end" name="horizon" type="date" value="${esc(p.horizon)}"><label for="plan-military">Expected military date <small>leave blank if uncertain</small></label><input id="plan-military" name="military" type="date" value="${esc(p.military)}">`}${actions('Save direction')}</form>`);
}
function noteModal(id,fromCapture,entryType='note') {
  const note=state.notes[id], captured=state.captures[fromCapture];entryType=note?.entryType||entryType;
  modal(note?'Edit your resource':entryType==='book'?'Add a book':entryType==='routine'?'Add an optional routine':'Save one useful thing.','Keep what you can use. It creates no new daily commitment.',`<form id="note-form"><input type="hidden" name="id" value="${esc(id||'')}"><input type="hidden" name="capture" value="${esc(fromCapture||'')}"><input type="hidden" name="entryType" value="${entryType}"><label for="note-title">Title</label><input id="note-title" name="title" required maxlength="200" value="${esc(note?.title||captured?.text.slice(0,100)||'')}"><label for="note-category">Topic</label><select id="note-category" name="category">${areaTopics().map(c=>`<option value="${esc(c)}" ${(note?.category||(entryType==='book'?'Books, history & economy':entryType==='routine'?'Fitness & recovery':category!=='All'?category:'Saved insights'))===c?'selected':''}>${esc(topicLabel(c))}</option>`).join('')}</select>
  ${entryType==='book'?`<label for="book-author">Author · optional</label><input id="book-author" name="author" maxlength="200" value="${esc(note?.author||'')}"><label for="book-status">Reading status</label><select id="book-status" name="readingStatus">${['To read','Reading','Finished','Paused'].map(v=>`<option ${note?.readingStatus===v?'selected':''}>${v}</option>`).join('')}</select><div class="form-row"><div><label for="book-pages">Pages read</label><input id="book-pages" name="pagesRead" type="number" min="0" value="${note?.pagesRead||0}"></div><div><label for="book-total">Total pages · optional</label><input id="book-total" name="pagesTotal" type="number" min="0" value="${note?.pagesTotal||0}"></div></div>`:entryType==='routine'?`<label for="routine-target">Flexible weekly target</label><input id="routine-target" name="routineTarget" type="number" min="1" max="7" required value="${note?.routineTarget||3}"><p>Check days in Plans → Optional routines. No broken-streak penalties.</p>`:''}
  <details><summary>Tags and goal link · optional</summary><label for="note-tags">Tags · separate with commas</label><input id="note-tags" name="tags" maxlength="500" value="${esc(note?.tags||'')}"><label for="note-goal">Linked goal</label><select id="note-goal" name="goal"><option value="">None</option>${records(state,'goals').map(g=>`<option value="${esc(g.id)}" ${note?.goal===g.id?'selected':''}>${esc(g.title)}</option>`).join('')}</select></details><label for="note-url">Resource link · optional</label><input id="note-url" name="url" type="url" placeholder="https://…" value="${esc(note?.url||'')}"><label for="note-body">${entryType==='book'?'One insight and how you will use it':'Practical note'}</label><textarea id="note-body" name="body" maxlength="20000" rows="5">${esc(note?.body||captured?.text||'')}</textarea>${actions('Save to Vault',note?`<button type="button" class="button ghost" data-action="archive-note" data-id="${esc(id)}">${note.archived?'Restore resource':'Archive resource'}</button><button type="button" class="button danger" data-action="delete-note" data-id="${esc(id)}">Delete resource</button>`:'')}</form>`);
}
function legacyModal(filter='All') {
  const entries = records(state,'legacy').filter(l=>l.category!=='Source archive'&&l.kind!=='goal-history');
  const groups = [...new Set(entries.map(l=>l.category))];
  modal('Your preserved records', 'All original fields are retained. Bring useful records into the Vault when needed.', `<label for="legacy-filter">Original category</label><select id="legacy-filter">${['All',...groups].map(g=>`<option ${filter===g?'selected':''}>${esc(g)}</option>`).join('')}</select>${entries.filter(l=>filter==='All'||l.category===filter).map(l=>{
    let original;try{original=JSON.parse(l.body);}catch{original={note:l.body};}
    return `<details class="review-entry"><summary>${esc(l.title)} · ${esc(l.category)}</summary>${Object.entries(original).map(([k,v])=>`<p><strong>${esc(k)}:</strong> ${esc(typeof v==='object'?JSON.stringify(v):v)}</p>`).join('')}<button class="button soft" data-action="legacy-note" data-id="${esc(l.id)}">Copy into an editable Vault note</button></details>`;
  }).join('') || '<p>No records in this category.</p>'}`);
}
function download(value, name, type='application/json') {
  const url=URL.createObjectURL(new Blob([typeof value==='string'?value:JSON.stringify(value,null,2)],{type}));
  const link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),15000);
}
function exportBackup() {
  if(recoveryLocked){download({current:localStorage.getItem(STORAGE_KEY),legacy:localStorage.getItem('governor-data')},`governor-original-storage-${today()}.json`);toast('Original storage exported for recovery. It is not a normal restorable backup.');return;}
  download(makeBackup(state),`governor-backup-${today()}.json`); toast('Backup downloaded. Keep it in a safe place.');
}
function settingsModal() {
  const config=loadConfig(), signed=!!cloud.session?.user;
  modal('Your app. Your data.', 'Free to use. Saves on this device first. Private cloud sync is optional until you connect it.', `<section class="settings-section"><h3>Main areas</h3><p>Choose your own sidebar shortcuts. Removing one keeps all its records.</p><button class="button subtle" data-action="manage-areas">Manage areas</button></section><section class="settings-section"><h3>Backups & migration</h3><p>Export before switching versions. Import merges records instead of replacing your current data. Governor and Second Brain JSON backups are supported. Account workspaces stay separate; export a local workspace before signing in if you want to import it into that account.</p><div class="backup-actions"><button class="button" data-action="export">Export backup</button><button class="button subtle" data-action="import">Import backup</button><input class="hidden" id="import-file" type="file" accept=".json,application/json">${storageError ? '<button class="button subtle" data-action="raw-export">Export original device storage</button>' : ''}</div><p>Backups contain personal notes. Keep them private. Sign-in credentials are excluded.</p>${records(state,'legacy').some(l=>l.source) ? '<button class="button ghost" data-action="source-export">Export untouched legacy source</button>' : ''}</section>
    <section class="settings-section"><h3>Private phone ↔ laptop sync</h3><p>${signed?`Signed in as ${esc(cloud.session.user.email)}. Edits merge automatically when online.`:'Connect your own free Supabase project, then sign in with the same email on both devices.'}</p><p id="cloud-message" class="form-error" role="status">${esc(cloud.lastError||'')}</p>${signed ? `<div class="backup-actions"><button class="button soft" data-action="sync-now">Sync now</button><button class="button subtle" data-action="sign-out">Sign out</button></div><p>Signing out hides this account’s records and opens a separate local workspace. Sign in again to resume. Browser copies are not encrypted; lock your device.</p>` : ''}<details ${!config?'open':''}><summary>Cloud connection</summary><form id="cloud-config-form"><label for="cloud-url">Project URL</label><input id="cloud-url" type="url" name="url" value="${esc(config?.url||'')}" placeholder="https://your-project.supabase.co" required><label for="cloud-key">Public publishable / anon key</label><input id="cloud-key" name="key" value="${esc(config?.key||'')}" placeholder="sb_publishable_…" required autocomplete="off"><p>Use a public key only. Never enter a secret or service-role key.</p><button class="button soft" type="submit">Save connection</button></form></details>${config&&!signed ? `<form id="cloud-signin-form"><label for="cloud-email">Your email</label><input id="cloud-email" name="email" type="email" required autocomplete="email"><button class="button" type="submit" style="margin-top:14px">Email me a sign-in link</button><p>Open the link on this device. No password is stored in the app.</p></form>` : ''}<p><a class="helper-link" href="./docs/cloud-setup.html" target="_blank" rel="noopener">Simple cloud setup guide ↗</a></p></section>
    <section class="settings-section"><h3>Independent accounts · optional</h3><p>Your current project was configured for its owner. Other people can use separate local workspaces now. Cloud saving for additional accounts requires a one-time permissions update; it is not yet verified on your live project.</p><button class="button subtle" data-action="multi-user-setup">Enable separate cloud accounts</button><p>Each person needs their own login. Never share your password or backup. Email delivery may require inviting accounts in Supabase.</p></section><section class="settings-section"><h3>Phone & offline use</h3><p>Gold edition · 20261009-r5 · <a href="./update.html">Refresh app files safely</a>. Updates keep your records and sign-in.</p><p>After one successful online visit, the app can reopen offline on supported browsers. Sync, sign-in and external links need internet. Keep regular backups; browsers can clear local storage.</p><p id="offline-state">${'serviceWorker' in navigator?'Checking offline installation…':'This browser does not support offline installation.'}</p><p>iPhone: Safari → Share → Add to Home Screen.<br>Android: Chrome menu → Install app / Add to Home screen.<br>Laptop: bookmark the same site, or install from your browser.</p><a class="helper-link" href="./docs/guide.html" target="_blank" rel="noopener">Short user guide ↗</a></section>`);
  if(config&&!signed) $('#cloud-signin-form').insertAdjacentHTML('afterend', `<details><summary>Use my existing email and password</summary><form id="cloud-password-form"><label for="password-email">Your email</label><input id="password-email" name="email" type="email" required autocomplete="username"><label for="cloud-password">Password</label><input id="cloud-password" name="password" type="password" required autocomplete="current-password"><button class="button soft" type="submit" style="margin-top:14px">Sign in</button><p>Your password is sent only to your own Supabase project over HTTPS. It is not saved or exported.</p></form></details>`);
  if(document.documentElement.hasAttribute('data-portable')) $('#offline-state').textContent='Portable copy: the app files are embedded in this HTML. Local daily work needs no network. Keep a separate exported data backup.';
  else if('serviceWorker' in navigator) navigator.serviceWorker.getRegistration().then(reg=>{ const node=$('#offline-state'); if(node)node.textContent=reg?.active?'Offline app files are installed on this device.':'Offline files are not installed yet. Reopen on HTTPS after an online visit.'; });
}

async function runAction(action,id) {
  switch(action) {
    case 'close': closeModal();break;
    case 'undo': {const f=undoAction;undoAction=null;if(f)f();break;}
    case 'capture': captureModal();break;
    case 'low-energy': edit('settings','mode',{value:state.settings.mode?.value==='low'?'normal':'low'},'Your pace is set.');break;
    case 'focus': if(!timer.end){timer.end=Date.now()+(timer.remaining||timer.duration*60)*1000;saveTimer();}updateTimer();$('#timer-toggle')?.focus();break;
    case 'add-parked': taskModal(null,today(),'',true);break;
    case 'add-task': taskModal();break;
    case 'edit-task': taskModal(id);break;
    case 'complete': {const t=state.tasks[id]; if(!t)return;if(!t.done&&t.paused)throw new Error('Choose this from Parked priorities before completing it.');edit('tasks',id,{done:!t.done,completedAt:t.done?'':today()},t.done?'Action reopened.':'Action completed. A useful step forward.');break;}
    case 'delete-task': modal('Delete this action?','This removes the action from your lists. You can undo immediately.',`<p>${esc(state.tasks[id].title)}</p><div class="modal-actions"><button class="button subtle" data-action="edit-task" data-id="${esc(id)}">Cancel</button><button class="button danger" data-action="confirm-delete-task" data-id="${esc(id)}">Confirm deletion</button></div>`);break;
    case 'confirm-delete-task': edit('tasks',id,{deleted:true},'Action deleted.');closeModal();break;
    case 'primary': {const t=state.tasks[id];edit('tasks',id,{order:Math.min(0,...openToday().map(t=>t.order||0))-1},'Primary action updated.');closeModal();break;}
    case 'park-task': edit('tasks',id,{paused:true},'Parked for later. Nothing lost.');closeModal();break;
    case 'parked': parkedModal();break;
    case 'bring-task': {
      if(openToday().length){toast('Finish or park the current priorities before choosing the next group.');return;}
      const next=structuredClone(state);focusParked(next,[id],device);write(next);closeModal();toast('Focused today. The earlier record is preserved.');break;
    }
    case 'edit-capture': captureModal(id);break;
    case 'inbox': inboxModal();break;
    case 'capture-note': noteModal(null,id);break;
    case 'delete-capture': {if($('#capture-form [name=id]')?.value===id)localStorage.removeItem('governor.capture.draft');edit('captures',id,{deleted:true},'Thought deleted. Undo is available.');const restore=undoAction;undoAction=()=>{restore();inboxModal();};inboxModal(true);break;}
    case 'archive-capture': edit('captures',id,{archived:true},'Thought archived.');inboxModal();break;
    case 'restore-capture': edit('captures',id,{archived:false},'Thought restored.');inboxModal();break;
    case 'checkin': checkinModal();break;
    case 'delete-review': modal('Delete this review?','You can export a backup before removing it.',`<div class="modal-actions"><button class="button subtle" data-action="close">Cancel</button><button class="button danger" data-action="confirm-delete-review" data-id="${esc(id)}">Confirm deletion</button></div>`);break;
    case 'confirm-delete-review': edit('reviews',id,{deleted:true},'Review deleted.');closeModal();break;
    case 'weekly': weeklyModal(id);break;
    case 'goal': goalModal(id);break;
    case 'add-goal': goalModal();break;
    case 'goal-history': goalHistoryModal(id);break;
    case 'deleted-goals': deletedGoalsModal();break;
    case 'delete-goal': modal('Delete this goal?', 'The goal leaves your plans. Earlier versions and linked actions remain saved.', `<p>${esc(state.goals[id].title)}</p><div class="modal-actions"><button class="button subtle" data-action="goal" data-id="${esc(id)}">Cancel</button><button class="button danger" data-action="confirm-delete-goal" data-id="${esc(id)}">Confirm deletion</button></div>`);break;
    case 'confirm-delete-goal': changeGoal(id,{deleted:true,status:'deleted',active:false},'Goal deleted. History and linked records retained.');closeModal();break;
    case 'goal-focus': {const g=state.goals[id];if(!g?.nextAction)return;const existing=dailyTasks(state).find(t=>t.goal===id&&t.action===g.nextAction&&!t.carriedTo);if(existing){if(existing.done){toast('This action is already completed today. Edit the goal’s next action when ready.');break;}if(existing.paused){if(openToday().length>=taskLimit(state))throw new Error('Park or complete one action before focusing another.');edit('tasks',existing.id,{paused:false},'Action focused today.');}zone='tunnel';location.hash='tunnel';render();break;}if(openToday().length>=taskLimit(state))throw new Error('Park or complete one action before focusing another.');edit('tasks',uid(),{title:g.title,action:g.nextAction,goal:id,date:today(),done:false,paused:false,order:openToday().length},'Next action focused today.');zone='tunnel';location.hash='tunnel';render();break;}
    case 'calendar': zone='compass';history.replaceState(null,'','#compass');render();$('#calendar-section').scrollIntoView({behavior:'instant',block:'start'});break;
    case 'calendar-day': calendarDayModal(id);break;
    case 'calendar-add': taskModal(null,id);break;
    case 'guide': guideModal();break;
    case 'search': searchModal();break;
    case 'area': category=id;query='';showArchive=false;zone='vault';location.hash='vault';render();window.scrollTo(0,0);break;
    case 'capture-task': taskModal(null,today(),id);break;
    case 'monthly': weeklyModal(id,'month');break;
    case 'book': noteModal(null,null,'book');break;
    case 'routine': noteModal(null,null,'routine');break;
    case 'routine-toggle': {const date=runAction.date,n=state.notes[id];if(!date||date>today()||n?.entryType!=='routine')break;const key=`routine-${id}-${date}`;edit('checkins',key,{date,note:n.title,energy:'routine',kind:'routine',routineId:id,done:!state.checkins[key]?.done},'Routine saved. Blank days are allowed.');break;}
    case 'delete-note': modal('Delete this resource?','Export a backup first if you want to keep a separate copy.',`<p>${esc(state.notes[id].title)}</p><div class="modal-actions"><button class="button subtle" data-action="note" data-id="${esc(id)}">Cancel</button><button class="button danger" data-action="confirm-delete-note" data-id="${esc(id)}">Confirm deletion</button></div>`);break;
    case 'confirm-delete-note': edit('notes',id,{deleted:true},'Resource deleted.');closeModal();break;
    case 'plan': planModal();break;
    case 'why': planModal(true);break;
    case 'note': noteModal(id);break;
    case 'note-task': {const n=state.notes[id], captureId=`note-${id}`;if(state.tasks[`capture-task-${captureId}`]&&!state.tasks[`capture-task-${captureId}`].deleted){taskModal(`capture-task-${captureId}`);break;}edit('captures',captureId,{sourceTitle:n.title,text:n.title+(n.body?'\n'+n.body.slice(0,1000):''),date:today(),archived:true},'',{undo:false,redraw:false});taskModal(null,today(),captureId);if(n.goal&&$('#task-goal'))$('#task-goal').value=n.goal;break;}
    case 'archive-note': edit('notes',id,{archived:!state.notes[id].archived},state.notes[id].archived?'Resource restored.':'Resource archived.');closeModal();break;
    case 'vault-archive': showArchive=!showArchive;render();break;
    case 'legacy': legacyModal();break;
    case 'legacy-note': {const l=state.legacy[id];let obj;try{obj=JSON.parse(l.body);}catch{obj={note:l.body};}edit('notes',`copy-${id}`,{title:l.title,category:'Saved insights',body:Object.entries(obj).map(([k,v])=>`${k}: ${typeof v==='object'?JSON.stringify(v):v}`).join('\n'),url:'',archived:false},'Copied into the Vault. Original preserved.');closeModal();break;}
    case 'timer-toggle': if(timer.end){timer.remaining=Math.max(0,Math.ceil((timer.end-Date.now())/1000));timer.end=0;}else{if(timer.remaining<=0)timer.remaining=timer.duration*60;timer.end=Date.now()+timer.remaining*1000;}saveTimer();updateTimer();break;
    case 'timer-reset': timer.end=0;timer.remaining=timer.duration*60;saveTimer();updateTimer();break;
    case 'multi-user-setup': {const response=await fetch('./multi-user.sql');if(!response.ok)throw new Error('Connect to the internet to load the account setup.');const sql=await response.text();const config=loadConfig(),ref=config?new URL(config.url).hostname.split('.')[0]:'';modal('Enable independent cloud accounts','Export your backup first. Only the project owner can change these database permissions. Saved rows stay untouched; older cloud archives become private read-only records.',`<p>Copy the text below, open your storage setup, paste it and press Run. Then create or invite each person in Authentication → Users.</p><textarea id="multi-user-sql" rows="12" readonly aria-label="Account permissions setup">${esc(sql)}</textarea><div class="modal-actions"><button class="button" data-action="copy-account-sql">Copy setup</button>${ref?`<a class="button subtle" href="https://supabase.com/dashboard/project/${encodeURIComponent(ref)}/sql/new" target="_blank" rel="noopener">Open storage setup ↗</a>`:''}<button class="button subtle" data-action="close">Close</button></div>`);break;}
    case 'copy-account-sql': try{await navigator.clipboard.writeText($('#multi-user-sql').value);toast('Copied. Paste in the storage setup and press Run.');}catch{$('#multi-user-sql').select();toast('Select and copy the setup text.');}break;
    case 'manage-areas': areasModal();break;
    case 'edit-area': areaModal(id);break;
    case 'toggle-area': {const area=mainAreas().find(a=>a.id===id);if(!area)break;edit('settings',area.id,{...area,deleted:false,visible:area.visible===false},area.visible===false?'Area restored.':'Shortcut removed. Your records are kept.');areasModal();break;}
    case 'settings': settingsModal();break;
    case 'export': exportBackup();break;
    case 'import': $('#import-file').click();break;
    case 'raw-export': download({current:localStorage.getItem(STORAGE_KEY),legacy:localStorage.getItem('governor-data')},`governor-original-storage-${today()}.json`);break;
    case 'source-export': {const sources=[...new Set(records(state,'legacy').map(l=>l.source).filter(Boolean))];for(const source of sources)download(recoverOriginal(state,source),`governor-legacy-original-${source}.json`);break;}
    case 'history-export': {const result={month:historyMonth,tasks:records(state,'tasks').filter(t=>taskHistoryDate(t).startsWith(historyMonth)),checkins:records(state,'checkins').filter(c=>c.date.startsWith(historyMonth)),reviews:records(state,'reviews').filter(r=>r.date.startsWith(historyMonth))};download(result,`governor-month-${historyMonth}.json`);toast('Month report downloaded. Use Export backup to make a restorable copy.');break;}
    case 'sync-now': await cloud.sync(); if($('#cloud-message'))$('#cloud-message').textContent=cloud.lastError||'Sync complete.';break;
    case 'sign-out': cloud.dispose();await cloud.signOut();location.reload();break;
  }
}
document.addEventListener('click', event=>{
  const target=event.target.closest('[data-action]');if(!target)return;
  event.preventDefault();runAction.date=target.dataset.date;Promise.resolve(runAction(target.dataset.action,target.dataset.id)).catch(error=>toast(error.message));
});
$('#settings-button').addEventListener('click',settingsModal);$('#capture-button').addEventListener('click',captureModal);
$('#modal').addEventListener('click',event=>{if(event.target===$('#modal')){const rect=$('#modal').getBoundingClientRect();if(event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom)closeModal();}});
$('#modal').addEventListener('close',()=>{if(focusReturn?.isConnected)focusReturn.focus();});
window.addEventListener('hashchange',()=>{ const route=location.hash.slice(1);if(['tunnel','compass','vault'].includes(route)){zone=route;render();window.scrollTo(0,0);$('#main').focus({preventScroll:true});} });
document.addEventListener('input',event=>{
  if(['capture-text','modal-capture'].includes(event.target.id)){try{localStorage.setItem('governor.capture.draft',event.target.value);}catch{}}
  if(event.target.id==='vault-search'){query=event.target.value;$('#note-grid').innerHTML=groupedNotes();}
});
document.addEventListener('change',async event=>{
  try{
    if(event.target.id==='energy-mode')edit('settings','mode',{value:event.target.value},'Your pace is set.');
    if(event.target.id==='timer-duration'){timer.duration=Number(event.target.value);timer.remaining=timer.duration*60;timer.end=0;saveTimer();updateTimer();}
    if(event.target.id==='vault-category'){category=event.target.value;render();}
    if(event.target.id==='history-month'){historyMonth=event.target.value||today().slice(0,7);$('#month-history').innerHTML=historyHTML();}
    if(event.target.id==='goal-tracking'){const tracking=event.target.value;$('#manual-fields').hidden=tracking!=='manual';$('#target-fields').hidden=tracking!=='target';}
    if(event.target.id==='goal-chart-metric'){goalChartMetric=event.target.value;render();}
    if(event.target.id==='goal-chart-scope'){goalChartScope=event.target.value;render();}
    if(event.target.id==='goal-filter'){goalFilter=event.target.value;render();}
    if(event.target.id==='chart-period'){chartPeriod=event.target.value;render();}
    if(event.target.id==='chart-month'){chartMonth=event.target.value||today().slice(0,7);render();}
    if(event.target.id==='calendar-month'){calendarMonth=event.target.value||today().slice(0,7);render();}
    if(event.target.id==='routine-week'){routineWeek=event.target.value||today();render();$('#main .routines-card details').open=true;}
    if(event.target.id==='legacy-filter')legacyModal(event.target.value);
    if(event.target.id==='import-file'){
      const file=event.target.files[0];if(!file)return;if(file.size>8000000)throw new Error('Choose a backup smaller than 8 MB.');
      const incoming=importFile(await file.text(),device);validateState(incoming);
      const existing=makeBackup(state);const merged=mergeStates(state,incoming);
      modal('Your import is ready.', 'Your current records will be kept. Matching records use the most recent edit. A backup of the current data will download before merging.', `<p class="modal-subtitle">${Object.keys(incoming.tasks).length} priorities · ${Object.keys(incoming.notes).length} notes · ${Object.keys(incoming.legacy).length} preserved legacy records</p><div class="modal-actions"><button class="button subtle" data-action="close">Cancel</button><button class="button" id="confirm-import">Back up & merge</button></div>`);
      $('#confirm-import').addEventListener('click',()=>{const wasLocked=recoveryLocked;try{if(wasLocked)download({current:localStorage.getItem(STORAGE_KEY),legacy:localStorage.getItem('governor-data')},`governor-original-storage-${today()}.json`);download(existing,`governor-before-import-${today()}.json`);recoveryLocked=false;write(mergeStates(state,merged));closeModal();toast('Import merged. Original and current records are preserved.');}catch(error){recoveryLocked=wasLocked;toast(error.message);}});
    }
  }catch(error){toast(error.message);}
});
document.addEventListener('submit',async event=>{
  event.preventDefault();const form=event.target;const formId=form.getAttribute('id');const f=Object.fromEntries(new FormData(form));const submit=form.querySelector('[type=submit]');
  if(submit)submit.disabled=true;
  try {
    if(['task-form','note-form','goal-form'].includes(formId)&&!f.title.trim())throw new Error('Give this a short, concrete name.');
    if(formId==='weekly-form'&&!f.wins.trim())throw new Error('Write one observation from this week. A difficult week is worth recording too.');
    switch(formId){
      case 'area-form': {const title=f.title.trim();if(!title)throw new Error('Give your area a name.');const areas=mainAreas(),old=areas.find(area=>area.id===f.id);if(areas.some(area=>area.id!==f.id&&area.title.toLowerCase()===title.toLowerCase()))throw new Error('This area already exists. Edit or restore it in Manage areas.');const topic=old?.topic||areaTopics().find(topic=>topic.toLowerCase()===title.toLowerCase())||title;if(!old&&areas.some(area=>area.topic===topic))throw new Error('This topic already has an area. Edit or restore that shortcut.');const id=old?.id||`main-area-${uid()}`;edit('settings',id,{kind:'main-area',deleted:false,title,topic,topicLabel:title,icon:AREA_ICONS[f.icon]?f.icon:'4',visible:old?.visible!==false,order:old?.order??Math.max(-1,...areas.map(area=>area.order||0))+1},'Area saved.');areasModal();break;}
      case 'task-form': {const id=f.id||(f.capture?`capture-task-${f.capture}`:uid()), old=state.tasks[id], date=f.date||today();const parked=f.parked==='1'||!!old?.paused;const count=dailyTasks(state,date).filter(t=>!t.done&&!t.paused&&!t.carriedTo&&t.id!==id).length;if(!parked&&(!old||old.date!==date)&&count>=(date===today()?taskLimit(state):3))throw new Error('This day already has enough priorities. Choose another day or park an action first.');if(f.capture&&old&&!old.deleted)throw new Error('This thought already has a priority. Edit that priority instead.');if(f.goal&&(!state.goals[f.goal]||state.goals[f.goal].deleted&&old?.goal!==f.goal))throw new Error('Choose an existing plan or Other.');const values={deleted:false,minutes:Number(f.minutes)||0,title:f.title.trim(),action:f.action.trim()||f.title.trim(),goal:f.goal,date,done:old?.done||false,paused:parked,order:old?.order??count};if(old&&!old.deleted&&old.date!==date){const next=structuredClone(state);const carried=carryTask(next,id,date,device,values);if(parked)put(next,'tasks',carried.id,{paused:true},device);write(next);toast('Rescheduled. Earlier records retained.');}else edit('tasks',id,values,'Priority saved.');if(f.capture){const next=structuredClone(state);put(next,'captures',f.capture,{archived:true},device);write(next);}closeModal();break;}
      case 'parked-focus-form': {const next=structuredClone(state);focusParked(next,new FormData(event.target).getAll('tasks'),device);write(next);closeModal();toast('Your next priorities are in focus. Parked work stays saved.');break;}
      case 'search-form': case 'top-search': searchModal(f.query||'');break;
      case 'inline-capture': case 'capture-form': {const text=f.text.trim();if(!text)throw new Error('Write a thought first.');edit('captures',f.id||uid(),{text,date:state.captures[f.id]?.date||today(),archived:state.captures[f.id]?.archived||false},'Thought saved. Back to your next action.',{redraw:false});localStorage.removeItem('governor.capture.draft');if($('#capture-text'))$('#capture-text').value='';if(formId==='capture-form')closeModal();else form.reset();break;}
      case 'checkin-form': edit('checkins',f.id,{date:today(),note:f.note.trim(),energy:f.energy},'Today’s check-in saved.');closeModal();break;
      case 'weekly-form': {const id=f.id||uid();edit('reviews',id,{date:state.reviews[id]?.date||today(),wins:f.wins.trim(),obstacles:f.obstacles.trim(),next:f.next.trim(),period:f.period||'week',archived:false},'Weekly review saved. One adjustment at a time.');closeModal();break;}
      case 'goal-form': {if(f.tracking==='target'&&!(Number(f.target)>0))throw new Error('Set a target greater than zero.');const values={horizon:f.horizon,startDate:f.startDate,title:f.title.trim(),subtitle:f.subtitle.trim(),outcome:f.outcome.trim(),milestone:f.milestone.trim(),evidence:f.evidence.trim(),status:f.status,tracking:f.tracking,progress:Number(f.progress),current:Number(f.current),target:Number(f.target),unit:f.unit.trim(),deadline:f.deadline,nextAction:f.nextAction.trim(),deleted:false};for(const n of [1,2,3]){values[`month${n}`]=f[`month${n}`].trim();values[`month${n}Done`]=f[`month${n}Done`]==='on';values[`month${n}Date`]=f[`month${n}Date`];values[`month${n}Evidence`]=f[`month${n}Evidence`].trim();}changeGoal(f.id||uid(),values,'Goal and progress saved.');closeModal();break;}
      case 'plan-form': if(f.start&&f.horizon&&f.horizon<f.start)throw new Error('The planning horizon must be on or after the sprint start.');edit('settings','plan',f,'Your direction is saved.');closeModal();break;
      case 'note-form': {if(f.url&&!safeURL(f.url))throw new Error('Use a link beginning with https:// or http://.');const next=structuredClone(state), id=f.id||(f.capture?`capture-note-${f.capture}`:uid());const fields={tags:f.tags.trim(),goal:f.goal,title:f.title.trim(),category:f.category,body:f.body.trim(),url:f.url.trim(),entryType:f.entryType||'note',archived:state.notes[id]?.archived||false};if(f.entryType==='book'){fields.author=f.author.trim();fields.readingStatus=f.readingStatus;fields.pagesRead=Number(f.pagesRead);fields.pagesTotal=Number(f.pagesTotal);if(fields.pagesTotal>0&&fields.pagesRead>fields.pagesTotal)throw new Error('Pages read cannot exceed total pages.');}if(f.entryType==='routine')fields.routineTarget=Number(f.routineTarget);put(next,'notes',id,fields,device);if(f.capture)put(next,'captures',f.capture,{archived:true},device);write(next);closeModal();toast('Saved in the Vault.');break;}
      case 'cloud-config-form': if(cloud.session)throw new Error('Sign out before changing your cloud project.');saveConfig(f.url.trim(),f.key.trim());cloud.config=loadConfig();cloud.lastError='';settingsModal();toast('Connection saved. Sign in to enable cloud sync.');break;
      case 'cloud-signin-form': await cloud.sendLink(f.email.trim());$('#cloud-message').textContent='Check your email. Open the sign-in link on this device. If there is no email, check spam and the project’s email limits.';break;
      case 'cloud-password-form': await cloud.signInPassword(f.email.trim(),f.password);form.reset();await cloud.sync();settingsModal();toast(cloud.lastError||'Signed in to your separate account workspace. Sync status shows whether upload succeeded.');break;
    }
  }catch(error){const target=$('#form-error')||$('#cloud-message');if(target)target.textContent=error.message;else toast(error.message);}
  finally{if(submit?.isConnected)submit.disabled=false;}
});
window.addEventListener('storage',event=>{if(localStorage.getItem(PROFILE_KEY)!==boundProfile){cloud.dispose();location.reload();return;}if(event.key==='governor.cloud.session.v1'){cloud.dispose();location.reload();return;}if(event.key===STORAGE_KEY&&event.newValue){if(profileCopy(boundProfile)!==event.newValue)return;try{const merged=mergeStates(state,JSON.parse(event.newValue));if(JSON.stringify(merged)!==JSON.stringify(state))write(merged);else{state=merged;render();}}catch{toast('Another tab contains unreadable data. Your open copy is preserved.');}}});
window.addEventListener('online',()=>cloud.sync());window.addEventListener('offline',()=>cloud.sync());
document.addEventListener('visibilitychange',()=>{if(!document.hidden){if(today()!==lastToday){lastToday=today();render();}cloud.sync();updateTimer();}});
function timerText(){const seconds=timer.end?Math.max(0,Math.ceil((timer.end-Date.now())/1000)):timer.remaining;return `${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;}
function updateTimer(){if(timer.end&&timer.end<=Date.now()){timer.end=0;timer.remaining=0;saveTimer();toast('Focus time is complete. Take a breath and choose what’s next.');}if($('#timer-display'))$('#timer-display').textContent=timerText();if($('#timer-toggle'))$('#timer-toggle').textContent=timer.end?'Pause':'Start Focus Session';if($('#timer-duration'))$('#timer-duration').disabled=!!timer.end;}
setInterval(updateTimer,1000);setInterval(()=>{if(!document.hidden)cloud.sync();},60000);
render();if(startupMessage)toast(startupMessage);
cloud.acceptLink().then(signed=>{if(signed)toast('Signed in to your separate account workspace. Sync status shows whether upload succeeded.');return cloud.sync();}).catch(error=>toast(error.message));
if(!document.documentElement.hasAttribute('data-portable') && 'serviceWorker' in navigator && (location.protocol==='https:'||['localhost','127.0.0.1'].includes(location.hostname))){
  // Public assets are one versioned release. A completed update never clears user storage.
  navigator.serviceWorker.addEventListener('controllerchange',()=>{
    const channel=new MessageChannel();
    channel.port1.onmessage=event=>{
      channel.port1.close();
      if(event.data?.release===document.querySelector('meta[name="governor-release"]')?.content)return;
      const editing=$('#modal')?.open || /^(INPUT|TEXTAREA|SELECT)$/.test(document.activeElement?.tagName||'');
      if(!editing)location.reload();
      else {toast('Your app update is ready. Save this edit, then open the update link in Settings.');}
    };
    navigator.serviceWorker.controller?.postMessage({type:'GOVERNOR_VERSION'},[channel.port2]);
  });
  navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).then(reg=>reg.update()).catch(()=>{
    if(navigator.onLine)toast('Offline installation failed. Your saved data remains on this device; retry online using the update link in Settings.');
  });
}
