const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
const BASE=process.env.GOVERNOR_TEST_URL||'http://127.0.0.1:4184/',checks=[],errors=[];
async function check(name,fn){await fn();checks.push(name);console.log('PASS '+name);}
(async()=>{
 fs.mkdirSync('test-results',{recursive:true});
 const browser=await chromium.launch({executablePath:process.env.GOVERNOR_CHROMIUM||'/usr/bin/chromium',headless:true}),context=await browser.newContext({viewport:{width:1536,height:1024},acceptDownloads:true}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 const saved=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('governor.os.v1'))),close=()=>page.locator('[aria-label="Close dialog"]').click(),row=name=>page.locator('.area-editor-row').filter({has:page.getByText(name,{exact:true})});
 await page.goto(BASE);await page.locator('.hero').waitFor();const original=await saved();let areaId;
 await check('old six main areas are retained; new area persists and opens its own Library topic',async()=>{
  assert.equal(await page.locator('.area-links [data-action=area]').count(),6);await page.getByRole('button',{name:'Manage main areas',exact:true}).click();await page.getByRole('button',{name:'＋ Add area',exact:true}).click();await page.locator('#area-title').fill('Photography');await page.locator('#area-icon').selectOption('4');await page.getByRole('button',{name:'Save area',exact:true}).click();await close();await page.reload();assert.equal(await page.locator('.area-links [data-action=area]').count(),7);
  await page.locator('.area-links').getByRole('button',{name:'Photography',exact:true}).click();assert.equal(await page.locator('#vault-category').inputValue(),'Photography');await page.locator('[data-action=note]').first().click();assert.equal(await page.locator('#note-category').inputValue(),'Photography');await page.locator('#note-title').fill('Camera settings');await page.locator('#note-body').fill('Original reference to retain');await page.getByRole('button',{name:'Save to Vault',exact:true}).click();await page.locator('#modal').waitFor({state:'hidden'});assert.equal(await page.locator('#note-grid .note-card').count(),1);areaId=Object.values((await saved()).settings).find(r=>r.kind==='main-area'&&r.topic==='Photography').id;
 });
 await check('renaming updates sidebar and Library labels without rewriting notes or goals',async()=>{
  const before=await saved();await page.getByRole('button',{name:'Manage main areas',exact:true}).click();await row('Photography').getByRole('button',{name:'Edit',exact:true}).click();await page.locator('#area-title').fill('Creative work');await page.getByRole('button',{name:'Save area',exact:true}).click();await close();assert.equal(await page.locator('.area-links').getByRole('button',{name:'Photography',exact:true}).count(),0);await page.locator('.area-links').getByRole('button',{name:'Creative work',exact:true}).click();assert.ok((await page.locator('#note-grid').innerText()).includes('Camera settings'));assert.equal(await page.locator('#vault-category option:checked').innerText(),'Creative work');const after=await saved();assert.deepEqual(after.notes,before.notes);assert.deepEqual(after.goals,before.goals);await page.locator('#vault-search').fill('Creative work');assert.equal(await page.locator('#note-grid .note-card').count(),1);
 });
 await check('removing and restoring default/custom shortcuts retains all linked resources',async()=>{
  const before=await saved();await page.getByRole('button',{name:'Manage main areas',exact:true}).click();await row('Creative work').getByRole('button',{name:'Remove',exact:true}).click();assert.equal(await page.locator('.area-links').getByRole('button',{name:'Creative work',exact:true}).count(),0);await row('BAUER / Site').getByRole('button',{name:'Remove',exact:true}).click();await close();await page.locator('#toast [data-action=undo]').click();assert.equal(await page.locator('.area-links').getByRole('button',{name:'BAUER / Site',exact:true}).count(),1);await page.getByRole('button',{name:'Manage main areas',exact:true}).click();await row('BAUER / Site').getByRole('button',{name:'Remove',exact:true}).click();await close();await page.reload();assert.equal(await page.locator('.area-links [data-action=area]').count(),5);await page.locator('#vault-search').fill('');await page.locator('#vault-category').selectOption('All');assert.ok((await page.locator('#note-grid').innerText()).includes('Camera settings'));await page.getByRole('button',{name:'Manage main areas',exact:true}).click();await row('Creative work').getByRole('button',{name:'Restore',exact:true}).click();await row('BAUER / Site').getByRole('button',{name:'Restore',exact:true}).click();await close();assert.equal(await page.locator('.area-links [data-action=area]').count(),7);const after=await saved();assert.deepEqual(after.notes,before.notes);assert.deepEqual(after.goals,before.goals);assert.deepEqual(after.tasks,original.tasks);
 });
 await check('backup round-trip restores area names, hidden shortcuts and notes without duplicates',async()=>{
  await page.getByRole('button',{name:'Manage main areas',exact:true}).click();await row('German & languages').getByRole('button',{name:'Remove',exact:true}).click();await close();await page.locator('#settings-button').click();const downloadPromise=page.waitForEvent('download');await page.locator('[data-action=export]').click();const download=await downloadPromise,file=await download.path(),backup=JSON.parse(fs.readFileSync(file,'utf8'));assert.equal(backup.data.settings[areaId].title,'Creative work');await close();
  const other=await browser.newContext(),p=await other.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(BASE);await p.locator('#settings-button').click();await p.locator('#import-file').setInputFiles(file);await p.locator('#confirm-import').click();await p.locator('#modal').waitFor({state:'hidden'});assert.equal(await p.locator('.area-links').getByRole('button',{name:'Creative work',exact:true}).count(),1);assert.equal(await p.locator('.area-links').getByRole('button',{name:'German & languages',exact:true}).count(),0);const restored=await p.evaluate(()=>JSON.parse(localStorage.getItem('governor.os.v1')));assert.deepEqual(restored.settings[areaId],backup.data.settings[areaId]);assert.equal(Object.values(restored.notes).filter(n=>n.title==='Camera settings').length,1);await other.close();
 });
 await check('mobile Settings can edit areas offline, with no overflow and saved changes after reload',async()=>{
  await page.setViewportSize({width:360,height:800});await page.evaluate(()=>navigator.serviceWorker.ready);await page.reload();await page.waitForFunction(()=>!!navigator.serviceWorker.controller);await context.setOffline(true);await page.locator('#mobile-settings').click();await page.getByRole('button',{name:'Manage areas',exact:true}).click();await row('Creative work').getByRole('button',{name:'Edit',exact:true}).click();await page.locator('#area-title').fill('Creative practice');await page.getByRole('button',{name:'Save area',exact:true}).click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.ok(await page.locator('#modal').evaluate(n=>n.getBoundingClientRect().right<=innerWidth));await page.screenshot({path:'test-results/areas-mobile.png',fullPage:true});await close();await page.reload();assert.equal((await saved()).settings[areaId].title,'Creative practice');await context.setOffline(false);await page.setViewportSize({width:1536,height:1024});
 });
 await check('area settings merge across two cloud sessions and stay separate across accounts (simulated service)',async()=>{
  const {initialState,mergeStates}=await import('../core.js'),serverRows={};
  async function device(account,initial){const c=await browser.newContext();await c.route('https://areas-fixture.supabase.co/**',async r=>{const req=r.request(),u=new URL(req.url()),headers={'access-control-allow-origin':'*','access-control-allow-headers':'apikey,authorization,content-type,prefer','access-control-allow-methods':'GET,POST,PATCH,OPTIONS'};if(req.method()==='OPTIONS')return r.fulfill({status:204,headers});const send=(value,status=200)=>r.fulfill({status,headers,contentType:'application/json',body:JSON.stringify(value)});const user=req.headers().authorization.replace('Bearer ','');if(u.pathname==='/rest/v1/governor_state')return send({},404);if(req.method()==='GET')return send(serverRows[user]?[serverRows[user]]:[]);const body=req.postDataJSON();if(req.method()==='POST'){serverRows[user]=body;return send([body],201);}if(req.method()==='PATCH'){if(serverRows[user].revision!==Number(u.searchParams.get('revision').slice(3)))return send([]);serverRows[user]={...serverRows[user],...body};return send([serverRows[user]]);}return send({},404);});
   await c.addInitScript(({account,initial})=>{if(!localStorage.getItem('governor.os.v1')){localStorage.setItem('governor.os.v1',JSON.stringify(initial));localStorage.setItem('governor.cloud.config.v1',JSON.stringify({url:'https://areas-fixture.supabase.co',key:'sb_publishable_fixture'}));localStorage.setItem('governor.cloud.session.v1',JSON.stringify({access_token:account,refresh_token:account,expires_at:4000000000,user:{id:account,email:account+'@example.com'}}));}},{account,initial});const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(BASE);await p.waitForFunction(()=>document.querySelector('#sync-status').textContent==='Cloud up to date');return {c,p};}
  const a=await device('alpha',await saved()),b=await device('alpha',initialState());assert.equal(await b.p.locator('.area-links').getByRole('button',{name:'Creative practice',exact:true}).count(),1);await a.c.setOffline(true);await a.p.getByRole('button',{name:'Manage main areas',exact:true}).click();await a.p.locator('.area-editor-row').filter({has:a.p.getByText('Creative practice',{exact:true})}).getByRole('button',{name:'Remove',exact:true}).click();await a.c.setOffline(false);await a.p.waitForFunction(()=>document.querySelector('#sync-status').textContent==='Cloud up to date');await b.p.locator('#settings-button').click();await b.p.locator('[data-action=sync-now]').click();await b.p.waitForFunction(()=>![...document.querySelectorAll('.area-links [data-action=area]')].some(n=>n.textContent.trim()==='Creative practice'));assert.equal(await b.p.locator('.area-links').getByRole('button',{name:'Creative practice',exact:true}).count(),0);
  const separate=await device('beta',initialState());assert.equal(await separate.p.locator('.area-links [data-action=area]').count(),6);assert.ok(!JSON.stringify(serverRows.beta.data).includes('Creative practice'));const merged=mergeStates(await saved(),serverRows.alpha.data);assert.equal(merged.settings[areaId].visible,false);await a.c.close();await b.c.close();await separate.c.close();
 });
 assert.deepEqual(errors,[]);fs.writeFileSync('test-results/areas-results.json',JSON.stringify({testedAt:new Date().toISOString(),url:BASE,checks,errors,cloud:'Two sessions/account separation tested with simulated API; private live account unavailable.'},null,2));await browser.close();console.log(`${checks.length} area workflows passed.`);
})().catch(e=>{console.error(e);process.exit(1)});
