const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
const BASE=process.env.GOVERNOR_TEST_URL||'http://127.0.0.1:4182',checks=[],errors=[];
async function check(name,f){await f();checks.push(name);console.log('PASS '+name);}
(async()=>{
const browser=await chromium.launch({executablePath:process.env.GOVERNOR_CHROMIUM||'/usr/bin/chromium',headless:true}),context=await browser.newContext({viewport:{width:1536,height:1024},acceptDownloads:true}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
const saved=p=>(p||page).evaluate(()=>JSON.parse(localStorage.getItem('governor.os.v1'))),close=()=>page.locator('[aria-label="Close dialog"]').click();
await check('approved dashboard composition, real empty charts and responsive screenshots',async()=>{
 await page.goto(BASE);assert.equal(await page.locator('.quick-grid button').count(),4);assert.equal(await page.locator('[data-chart]').count(),2);assert.equal(await page.locator('.priority').count(),3);
 const positions=await page.evaluate(()=>({hero:document.querySelector('.hero').getBoundingClientRect().y,charts:document.querySelector('.charts-grid').getBoundingClientRect().y,sidebar:document.querySelector('.sidebar').getBoundingClientRect().width}));assert.equal(positions.sidebar,250);assert.ok(positions.hero<100);assert.ok(positions.charts<800);
 await page.screenshot({path:'test-results/handoff-desktop.png',fullPage:true});for(const width of [360,390,768,1024]){await page.setViewportSize({width,height:800});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`${width}px overflow`);await page.screenshot({path:`test-results/handoff-${width}.png`,fullPage:true});}await page.setViewportSize({width:1536,height:1024});
});
await check('task durations, delete confirmation, reopen and undo persist',async()=>{
 await page.locator('.priority [data-action=edit-task]').first().click();await page.locator('#task-minutes').fill('35');await page.getByRole('button',{name:'Save priority',exact:true}).click();await page.locator('#modal').waitFor({state:'hidden'});assert.equal((await saved()).tasks['starter-bauer'].minutes,35);
 await page.locator('.priority [data-action=edit-task]').first().click();await page.locator('[data-action=delete-task]').click();assert.ok(!(await saved()).tasks['starter-bauer'].deleted);await page.locator('[data-action=confirm-delete-task]').click();assert.equal((await saved()).tasks['starter-bauer'].deleted,true);await page.locator('#toast [data-action=undo]').click();assert.equal((await saved()).tasks['starter-bauer'].deleted,false);await page.reload();assert.equal((await saved()).tasks['starter-bauer'].minutes,35);
});
await check('focus duration, start, pause, reset and low-energy quick actions work',async()=>{
 await page.locator('#timer-duration').selectOption('10');await page.locator('[data-action=focus]').click();assert.equal(await page.locator('#timer-toggle').innerText(),'Pause');await page.locator('#timer-toggle').click();assert.ok(!(await page.locator('#timer-duration').isDisabled()));await page.locator('[data-action=timer-reset]').click();assert.equal(await page.locator('#timer-display').innerText(),'10:00');await page.locator('[data-action=low-energy]').click();assert.equal(await page.locator('.priority-list').first().locator('.priority').count(),1);await page.locator('[data-action=low-energy]').click();assert.equal(await page.locator('.priority-list').first().locator('.priority').count(),3);
});
await check('dated milestones with evidence drive charts and appear in calendar',async()=>{
 await page.locator('[data-zone=compass]').click();await page.locator('[data-action=goal][data-id=bauer]').click();await page.locator('#goal-tracking').selectOption('milestones');await page.getByText('Monthly milestones',{exact:true}).click();await page.locator('#milestone-date-1').fill('2026-11-10');await page.locator('#milestone-evidence-1').fill('Verified quantities workbook');await page.locator('[name=month1Done]').check();await page.getByRole('button',{name:'Save milestone',exact:true}).click();await page.locator('#modal').waitFor({state:'hidden'});assert.equal((await saved()).goals.bauer.progress,33);assert.equal(await page.locator('[data-chart=goals] [data-goal-id=bauer] strong').innerText(),'33%');await page.locator('#calendar-month').fill('2026-11');await page.locator('[data-action=calendar-day][data-id="2026-11-10"]').click();assert.ok((await page.locator('#modal-content').innerText()).includes('BAUER'));await close();
});
await check('tagged notes can link to goals and become a single editable priority',async()=>{
 await page.locator('[data-zone=vault]').click();await page.locator('[data-action=note]').first().click();await page.locator('#note-title').fill('A report idea');await page.locator('#note-body').fill('Check quantity totals against source records');await page.locator('#modal details').filter({hasText:'Tags and goal link'}).locator('summary').click();await page.locator('#note-tags').fill('quantities, site-controls');await page.locator('#note-goal').selectOption('bauer');await page.getByRole('button',{name:'Save to Vault',exact:true}).click();await page.locator('#modal').waitFor({state:'hidden'});await page.locator('#vault-search').fill('site-controls');assert.equal(await page.locator('#note-grid .note-card').count(),1);
 await page.locator('[data-zone=tunnel]').click();await page.locator('.hero [data-action=complete]').click();await page.locator('[data-zone=vault]').click();await page.locator('#vault-search').fill('site-controls');await page.locator('#note-grid [data-action=note-task]').click();await page.getByRole('button',{name:'Save priority',exact:true}).click();await page.locator('#modal').waitFor({state:'hidden'});assert.equal(Object.values((await saved()).tasks).filter(t=>t.title==='A report idea').length,1);await page.locator('#note-grid [data-action=note-task]').click();assert.equal(await page.locator('#task-title').inputValue(),'A report idea');assert.equal(await page.locator('#task-goal').inputValue(),'bauer');await close();
});
await check('Second Brain JSON import, editing and round-trip export retain usable records',async()=>{
 await page.locator('#settings-button').click();await page.locator('#import-file').setInputFiles('tests/fixtures/second-brain.json');await page.locator('#confirm-import').click();await page.locator('#modal').waitFor({state:'hidden'});const state=await saved();assert.ok(Object.values(state.notes).some(n=>n.entryType==='routine'));assert.ok(Object.values(state.notes).some(n=>n.title==='How I learn'));assert.ok(Object.values(state.tasks).some(t=>t.status==='Done'||t.done));await page.locator('[data-zone=vault]').click();await page.locator('#vault-search').fill('Deep Work');await page.locator('#note-grid [data-action=note]').click();assert.equal(await page.locator('#book-author').inputValue(),'Cal Newport');await close();await page.locator('#settings-button').click();const downloading=page.waitForEvent('download');await page.locator('[data-action=export]').click();const backup=JSON.parse(fs.readFileSync(await (await downloading).path(),'utf8'));assert.deepEqual(backup.data,state);await close();
});
await check('separate accounts do not mix browser copies; sign-out hides account records; two tabs follow account changes (simulated service)',async()=>{
 const c=await browser.newContext(),p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));const rows={};
 await c.route('https://separate-test.supabase.co/**',async r=>{const req=r.request(),url=new URL(req.url()),method=req.method(),body=method==='POST'||method==='PATCH'?req.postDataJSON():null;const headers={'access-control-allow-origin':'*','access-control-allow-headers':'apikey,authorization,content-type,prefer','access-control-allow-methods':'GET,POST,PATCH,OPTIONS'};const send=(data,status=200)=>r.fulfill({status,headers,contentType:'application/json',body:JSON.stringify(data)});if(method==='OPTIONS')return r.fulfill({status:204,headers});if(url.pathname==='/auth/v1/token'){const id=body.email==='alpha@example.com'?'alpha':'beta';return send({access_token:id,refresh_token:id,expires_at:Date.now()/1000+3600,user:{id,email:body.email}});}if(url.pathname==='/auth/v1/logout')return send({});const id=(req.headers().authorization||'').replace('Bearer ','');if(url.pathname==='/rest/v1/governor_state')return send({},404);if(url.pathname==='/rest/v1/governor_data'){if(method==='GET')return send(rows[id]?[structuredClone(rows[id])]:[]);if(method==='POST'){assert.equal(body.user_id,id);rows[id]=body;return send([body],201);}if(method==='PATCH'){rows[id]={...rows[id],...body};return send([rows[id]]);}}return send({},404);});
 await p.goto(BASE);await p.locator('#settings-button').click();await p.locator('#cloud-url').fill('https://separate-test.supabase.co');await p.locator('#cloud-key').fill('sb_publishable_fixture');await p.getByRole('button',{name:'Save connection',exact:true}).click();
 async function login(email){await p.locator('#modal details').filter({hasText:'Use my existing email and password'}).locator('summary').click();await p.locator('#password-email').fill(email);await p.locator('#cloud-password').fill('fixture-not-real');await p.getByRole('button',{name:'Sign in',exact:true}).click();await p.waitForFunction(()=>document.querySelector('#sync-status').textContent==='Cloud up to date');await p.locator('[aria-label="Close dialog"]').click();}
 await login('alpha@example.com');await p.locator('#capture-text').fill('Alpha confidential');await p.locator('#inline-capture button').click();await p.waitForFunction(()=>document.querySelector('#sync-status').textContent==='Cloud up to date');const tab=await c.newPage();tab.on('pageerror',e=>errors.push(e.message));await tab.goto(BASE);assert.ok(Object.values((await saved(tab)).captures).some(n=>n.text==='Alpha confidential'));
 await p.locator('#settings-button').click();await p.locator('[data-action=sign-out]').click();await p.waitForFunction(()=>!localStorage.getItem('governor.cloud.session.v1'));await p.locator('.hero').waitFor();assert.ok(!Object.values((await saved(p)).captures).some(n=>n.text==='Alpha confidential'));await p.locator('#settings-button').click();await login('beta@example.com');assert.ok(!Object.values((await saved(p)).captures).some(n=>n.text==='Alpha confidential'));await p.locator('#capture-text').fill('Beta confidential');await p.locator('#inline-capture button').click();await p.waitForFunction(()=>document.querySelector('#sync-status').textContent==='Cloud up to date');await tab.waitForFunction(()=>JSON.parse(localStorage.getItem('governor.cloud.session.v1'))?.user?.id==='beta');await tab.waitForFunction(()=>document.querySelector('#account-button').textContent==='BE');assert.ok(!Object.values((await saved(tab)).captures).some(n=>n.text==='Alpha confidential'));
 await p.locator('#settings-button').click();await p.locator('[data-action=sign-out]').click();await p.waitForFunction(()=>!localStorage.getItem('governor.cloud.session.v1'));await p.locator('.hero').waitFor();await p.locator('#settings-button').click();await login('alpha@example.com');const restored=await saved(p);assert.ok(Object.values(restored.captures).some(n=>n.text==='Alpha confidential'));assert.ok(!Object.values(restored.captures).some(n=>n.text==='Beta confidential'));assert.ok(!JSON.stringify(rows.beta.data).includes('Alpha confidential'));assert.ok(!JSON.stringify(rows.alpha.data).includes('Beta confidential'));await c.close();
});
assert.deepEqual(errors,[]);fs.writeFileSync('test-results/handoff-results.json',JSON.stringify({testedAt:new Date().toISOString(),url:BASE,checks,errors,cloud:'Simulated multi-account API; live authenticated RLS requires project owner setup and two real accounts.'},null,2));await browser.close();console.log(`${checks.length} handoff workflows passed.`);
})().catch(e=>{console.error(e);process.exit(1)});
