const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
const BASE=process.env.GOVERNOR_TEST_URL||'http://127.0.0.1:4184/',checks=[],errors=[];
async function check(name,fn){await fn();checks.push(name);console.log('PASS '+name);}
(async()=>{
 fs.mkdirSync('test-results',{recursive:true});
 const browser=await chromium.launch({executablePath:process.env.GOVERNOR_CHROMIUM||'/usr/bin/chromium',headless:true}),context=await browser.newContext({viewport:{width:1536,height:1024},acceptDownloads:true}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(BASE);
 const saved=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('governor.os.v1'))),close=()=>page.locator('[aria-label="Close dialog"]').click();
 const percent=id=>page.locator(`[data-chart=goals] [data-goal-id="${id}"] strong`).innerText();
 const reveal=async locator=>{if(!await locator.isVisible())await locator.locator('xpath=ancestor::details[1]').locator('summary').first().click();};
 const taskEdit=async(id,goal)=>{const edit=page.locator(`[data-action=edit-task][data-id="${id}"]`).first();await reveal(edit);await edit.click();await page.locator('#task-goal').selectOption(goal);await page.getByRole('button',{name:'Save priority',exact:true}).click();await page.locator('#modal').waitFor({state:'hidden'});};
 const complete=async id=>{const button=page.locator(`.priority [data-action=complete][data-id="${id}"]`);await reveal(button);await button.click();};
 let monthId,yearId;
 await check('new paused plans with 30-day and yearly horizons immediately populate Supports',async()=>{
  await page.locator('[data-zone=compass]').click();
  for(const [title,horizon] of [['30-day strength plan','30 days'],['Yearly career plan','1 year']]){
   await page.locator('[data-action=add-goal]').click();await page.locator('#goal-title').fill(title);await page.locator('#goal-outcome').fill('Build useful capability with daily practice.');await page.locator('#goal-horizon').selectOption(horizon);await page.getByRole('button',{name:'Create goal',exact:true}).click();await page.locator('#modal').waitFor({state:'hidden'});
  }
  const s=await saved();monthId=Object.values(s.goals).find(g=>g.title==='30-day strength plan').id;yearId=Object.values(s.goals).find(g=>g.title==='Yearly career plan').id;assert.equal(s.goals[monthId].status,'paused');assert.ok(s.goals[monthId].startDate);assert.equal(await percent(monthId),'0%');assert.equal(await percent(yearId),'0%');
  await page.locator('[data-zone=tunnel]').click();await page.locator('[data-action=edit-task][data-id=starter-bauer]').click();const options=await page.locator('#task-goal option').allTextContents();assert.ok(options.some(t=>t.includes('30-day strength plan')));assert.ok(options.some(t=>t.includes('Yearly career plan')));assert.ok(options.some(t=>t.startsWith('Other')));await close();await taskEdit('starter-bauer',monthId);
 });
 await check('completed days update the linked plan independently of the daily task total; reopening reverses them',async()=>{
  await complete('starter-bauer');assert.equal(await percent(monthId),'3.3%');assert.ok((await page.locator('.day-card').innerText()).includes('1 / 3'));
  await taskEdit('starter-kaitech',monthId);await complete('starter-kaitech');assert.equal(await percent(monthId),'3.3%');assert.ok((await page.locator('.day-card').innerText()).includes('2 / 3'));
  await complete('starter-bauer');assert.equal(await percent(monthId),'3.3%');await complete('starter-kaitech');assert.equal(await percent(monthId),'0%');
 });
 await check('reassigning a completed priority moves its day to its yearly plan; Other stays unlinked',async()=>{
  await complete('starter-kaitech');await taskEdit('starter-kaitech',yearId);assert.equal(await percent(monthId),'0%');assert.equal(await percent(yearId),'0.3%');await taskEdit('starter-kaitech','');assert.equal(await percent(yearId),'0%');assert.ok((await page.locator('.day-card').innerText()).includes('1 / 3'));
  await taskEdit('starter-bauer',yearId);await complete('starter-bauer');assert.equal(await percent(yearId),'0.3%');await page.reload();assert.equal(await percent(yearId),'0.3%');
 });
 await check('editing the plan horizon updates the chart without overwriting its outcome target; JSON restores the same records',async()=>{
  await page.locator('[data-zone=compass]').click();await page.locator('#goal-filter').selectOption('paused');await page.locator(`[data-action=goal][data-id="${yearId}"]`).click();await page.locator('#goal-horizon').selectOption('30 days');await page.locator('#goal-tracking').selectOption('target');await page.locator('#goal-current').fill('2');await page.locator('#goal-target').fill('10');await page.getByRole('button',{name:'Save milestone',exact:true}).click();await page.locator('#modal').waitFor({state:'hidden'});assert.equal(await percent(yearId),'3.3%');await page.locator('#goal-chart-metric').selectOption('outcomes');assert.equal(await percent(yearId),'20%');assert.equal((await saved()).goals[yearId].current,2);await page.locator('#goal-chart-metric').selectOption('days');
  await page.locator('#settings-button').click();const downloading=page.waitForEvent('download');await page.getByRole('button',{name:'Export backup',exact:true}).click();const d=await downloading,backup=JSON.parse(fs.readFileSync(await d.path(),'utf8')),original=await saved();await page.locator('[data-action=import]').click();await page.locator('#import-file').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});await page.locator('#confirm-import').click();assert.deepEqual(await saved(),original);await page.reload();assert.equal(await percent(yearId),'3.3%');
 });
 await check('thought deletion works in the inbox, archive and editor, supports undo and persists after refresh',async()=>{
  await page.locator('[data-zone=tunnel]').click();await page.locator('#capture-text').fill('An idea I can remove');await page.locator('#inline-capture button').click();await page.locator('[data-action=inbox]').click();let id=Object.values((await saved()).captures).find(c=>c.text==='An idea I can remove').id;await page.locator(`[data-action=delete-capture][data-id="${id}"]`).click();assert.equal((await saved()).captures[id].deleted,true);await page.getByRole('button',{name:'Undo deletion',exact:true}).click();assert.equal((await saved()).captures[id].deleted,false);assert.equal(await page.locator(`[data-action=delete-capture][data-id="${id}"]`).count(),1);await page.locator(`[data-action=archive-capture][data-id="${id}"]`).click();await page.getByText('Archived thoughts',{exact:true}).click();await page.locator(`[data-action=delete-capture][data-id="${id}"]`).click();assert.equal((await saved()).captures[id].deleted,true);await page.getByRole('button',{name:'Undo deletion',exact:true}).click();await page.getByText('Archived thoughts',{exact:true}).click();await page.locator(`[data-action=restore-capture][data-id="${id}"]`).click();await page.locator(`[data-action=edit-capture][data-id="${id}"]`).click();await page.getByRole('button',{name:'Delete thought',exact:true}).click();await close();await page.reload();assert.equal((await saved()).captures[id].deleted,true);await page.locator('[data-action=inbox]').click();assert.equal(await page.locator(`[data-action=delete-capture][data-id="${id}"]`).count(),0);await close();
 });
 await check('mobile offline task-to-plan edits persist and both charts fit at 360px',async()=>{
  await page.setViewportSize({width:360,height:800});await page.evaluate(()=>navigator.serviceWorker.ready);await page.reload();await page.waitForFunction(()=>!!navigator.serviceWorker.controller);await context.setOffline(true);await taskEdit('starter-capacity',monthId);await complete('starter-capacity');await page.reload();assert.equal(await percent(monthId),'3.3%');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:'test-results/linked-plans-mobile.png',fullPage:true});await page.locator('[data-zone=compass]').click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await context.setOffline(false);
 });
 await check('two simulated cloud sessions merge plan links, completion days and thought deletion without crossing accounts',async()=>{
  const {initialState}=await import('../core.js'),rows={};
  async function device(account,initial){const c=await browser.newContext();await c.route('https://links-fixture.supabase.co/**',async r=>{const req=r.request(),u=new URL(req.url()),headers={'access-control-allow-origin':'*','access-control-allow-headers':'apikey,authorization,content-type,prefer','access-control-allow-methods':'GET,POST,PATCH,OPTIONS'};if(req.method()==='OPTIONS')return r.fulfill({status:204,headers});const send=(v,status=200)=>r.fulfill({status,headers,contentType:'application/json',body:JSON.stringify(v)});const user=req.headers().authorization.replace('Bearer ','');if(u.pathname==='/rest/v1/governor_state')return send({},404);if(req.method()==='GET')return send(rows[user]?[rows[user]]:[]);const body=req.postDataJSON();if(req.method()==='POST'){rows[user]=body;return send([body],201);}if(req.method()==='PATCH'){if(rows[user].revision!==Number(u.searchParams.get('revision').slice(3)))return send([]);rows[user]={...rows[user],...body};return send([rows[user]]);}return send({},404);});await c.addInitScript(({account,initial})=>{if(!localStorage.getItem('governor.os.v1')){localStorage.setItem('governor.os.v1',JSON.stringify(initial));localStorage.setItem('governor.cloud.config.v1',JSON.stringify({url:'https://links-fixture.supabase.co',key:'sb_publishable_fixture'}));localStorage.setItem('governor.cloud.session.v1',JSON.stringify({access_token:account,refresh_token:account,expires_at:4000000000,user:{id:account,email:account+'@example.com'}}));}},{account,initial});const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(BASE);await p.waitForFunction(()=>document.querySelector('#sync-status').textContent==='Cloud up to date');return {c,p};}
  const seed=await saved(),a=await device('alpha',seed),b=await device('alpha',initialState()),separate=await device('beta',initialState());assert.equal(await b.p.locator(`[data-chart=goals] [data-goal-id="${monthId}"] strong`).innerText(),'3.3%');assert.equal(await separate.p.locator(`[data-chart=goals] [data-goal-id="${monthId}"]`).count(),0);
  await a.c.setOffline(true);const cloudEdit=a.p.locator('[data-action=edit-task][data-id=starter-capacity]');if(!await cloudEdit.isVisible())await cloudEdit.locator('xpath=ancestor::details[1]').locator('summary').first().click();await cloudEdit.click();await a.p.locator('#task-goal').selectOption(yearId);await a.p.getByRole('button',{name:'Save priority',exact:true}).click();await a.p.locator('#modal').waitFor({state:'hidden'});await a.c.setOffline(false);await a.p.waitForFunction(()=>document.querySelector('#sync-status').textContent==='Cloud up to date');await b.p.locator('#settings-button').click();await b.p.locator('[data-action=sync-now]').click();await b.p.waitForFunction(({monthId})=>document.querySelector(`[data-chart=goals] [data-goal-id="${monthId}"] strong`).textContent==='0%',{monthId});assert.equal(rows.alpha.data.tasks['starter-capacity'].goal,yearId);assert.ok(!rows.beta.data.goals[monthId]);assert.ok(Object.values(rows.alpha.data.captures).some(c=>c.text==='An idea I can remove'&&c.deleted));await a.c.close();await b.c.close();await separate.c.close();
 });
 assert.deepEqual(errors,[]);fs.writeFileSync('test-results/linked-plans-results.json',JSON.stringify({testedAt:new Date().toISOString(),url:BASE,checks,errors,cloud:'Two-session/account API is simulated, not live authenticated Supabase.'},null,2));await browser.close();console.log(`${checks.length} linked-plan workflows passed.`);
})().catch(e=>{console.error(e);process.exit(1)});
