const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
const BASE=process.env.GOVERNOR_TEST_URL||'http://127.0.0.1:4184/',checks=[],errors=[];
async function check(name,fn){await fn();checks.push(name);console.log('PASS '+name);}
(async()=>{
 fs.mkdirSync('test-results',{recursive:true});const browser=await chromium.launch({executablePath:process.env.GOVERNOR_CHROMIUM||'/usr/bin/chromium',headless:true}),context=await browser.newContext({viewport:{width:1536,height:1024},acceptDownloads:true}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(BASE);
 const saved=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('governor.os.v1'))),close=()=>page.locator('[aria-label="Close dialog"]').click();let ids;
 await check('six extra priorities can be added directly while three stay in focus; each retains Supports',async()=>{
  for(let n=1;n<=6;n++){await page.locator('.parked-lane [data-action=add-parked]').click();await page.locator('#task-title').fill('Parked work '+n);await page.locator('#task-action').fill('Finish concrete output '+n);await page.locator('#task-goal').selectOption(n%2?'bauer':'kaitech');await page.getByRole('button',{name:'Save parked priority',exact:true}).click();await page.locator('#modal').waitFor({state:'hidden'});}
  const s=await saved();ids=Object.values(s.tasks).filter(t=>t.paused).map(t=>t.id);assert.equal(ids.length,6);assert.equal(Object.values(s.tasks).length,9);assert.equal(await page.locator('.parked-priority').count(),6);assert.equal(await page.locator('.priorities-panel .priority:not(.done)').count(),3);assert.ok((await page.locator('.day-card').innerText()).includes('0 / 3'));assert.equal(await page.locator('[data-chart=goals] [data-goal-id=bauer] strong').innerText(),'0%');assert.equal(Object.values(s.captures).length,0);assert.equal(await page.locator('.parked-lane [data-action=parked]').isDisabled(),true);
 });
 await check('the next group stays locked until the current three finish; at most three parked tasks move together',async()=>{
  await page.locator('[data-action=complete][data-id=starter-bauer]').first().click();assert.equal(await page.locator('.parked-lane [data-action=parked]').isDisabled(),true);await page.locator('[data-action=complete][data-id=starter-kaitech]').first().click();assert.equal(await page.locator('.parked-lane [data-action=parked]').isDisabled(),true);await page.locator('[data-action=complete][data-id=starter-capacity]').first().click();assert.equal(await page.locator('.parked-lane [data-action=parked]').isDisabled(),false);
  await page.locator('.parked-lane [data-action=parked]').click();for(const id of ids.slice(0,4))await page.locator(`[name=tasks][value="${id}"]`).check();await page.getByRole('button',{name:'Focus selected priorities',exact:true}).click();assert.ok((await page.locator('#form-error').innerText()).includes('1 to 3'));assert.equal(Object.values((await saved()).tasks).filter(t=>t.paused).length,6);await page.locator(`[name=tasks][value="${ids[3]}"]`).uncheck();await page.getByRole('button',{name:'Focus selected priorities',exact:true}).click();await page.locator('#modal').waitFor({state:'hidden'});assert.equal(await page.locator('.priorities-panel .priority:not(.done)').count(),3);assert.equal(await page.locator('.parked-priority').count(),3);assert.ok((await page.locator('.day-card').innerText()).includes('3 / 6'));assert.equal(Object.values((await saved()).tasks).length,9);for(const id of ids.slice(0,3))assert.equal((await saved()).tasks[id].done,false);
 });
 await check('a parked task counts only after focus and completion; edits, reopening and backups retain the queue',async()=>{
  const id=ids[0];await page.locator(`.priority [data-action=complete][data-id="${id}"]`).click();assert.ok((await page.locator('.day-card').innerText()).includes('4 / 6'));assert.equal(await page.locator('[data-chart=goals] [data-goal-id=bauer] strong').innerText(),'1.1%');const detail=page.locator('.priorities-panel details');await detail.locator('summary').click();await page.locator(`.priority [data-action=complete][data-id="${id}"]`).click();assert.equal((await saved()).tasks[id].done,false);
  await page.locator(`.parked-lane [data-action=edit-task][data-id="${ids[3]}"]`).click();await page.locator('#task-title').fill('Edited parked output');await page.locator('#task-goal').selectOption('capacity');await page.getByRole('button',{name:'Save priority',exact:true}).click();await page.locator('#modal').waitFor({state:'hidden'});assert.equal((await saved()).tasks[ids[3]].paused,true);await page.locator('#settings-button').click();const downloading=page.waitForEvent('download');await page.getByRole('button',{name:'Export backup',exact:true}).click();const d=await downloading,backup=JSON.parse(fs.readFileSync(await d.path(),'utf8')),original=await saved();await page.locator('[data-action=import]').click();await page.locator('#import-file').setInputFiles({name:'parked.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});await page.locator('#confirm-import').click();assert.deepEqual(await saved(),original);await page.reload();assert.equal(await page.locator('.parked-priority').count(),3);
 });
 await check('mobile offline entry creates parked work without exceeding the focus limit or losing it on refresh',async()=>{
  await page.setViewportSize({width:360,height:800});await page.evaluate(()=>navigator.serviceWorker.ready);await page.reload();await page.waitForFunction(()=>!!navigator.serviceWorker.controller);await context.setOffline(true);await page.locator('.parked-lane [data-action=add-parked]').click();await page.locator('#task-title').fill('Offline parked priority');await page.locator('#task-goal').selectOption('bauer');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.getByRole('button',{name:'Save parked priority',exact:true}).click();await page.locator('#modal').waitFor({state:'hidden'});await page.reload();assert.equal(await page.locator('.parked-priority').count(),4);assert.equal(await page.locator('.priorities-panel .priority:not(.done)').count(),3);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:'test-results/parked-mobile.png',fullPage:true});await context.setOffline(false);
 });
 assert.deepEqual(errors,[]);fs.writeFileSync('test-results/parked-results.json',JSON.stringify({testedAt:new Date().toISOString(),url:BASE,checks,errors},null,2));await browser.close();console.log(`${checks.length} parked-priority workflows passed.`);
})().catch(e=>{console.error(e);process.exit(1)});
